<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('gateway_payments', function (Blueprint $table) {
            $table->id();
            $table->foreignId('client_id')->constrained('gateway_clients')->cascadeOnDelete();

            // Order IDs
            $table->string('internal_order_id')->unique();  // pgw_pay_xxxxx (generated by us)
            $table->string('external_order_id');            // merchant's own order ID

            // Money
            $table->decimal('amount', 12, 2);               // Full amount client charged their customer
            $table->string('currency', 3)->default('EGP');
            $table->decimal('commission_rate', 5, 2)->default(40.00);
            $table->decimal('commission_amount', 12, 2)->nullable(); // 40% → Musoftware
            $table->decimal('net_amount', 12, 2)->nullable();        // 60% → client

            // Customer info (passed by the client/merchant)
            $table->string('customer_name')->nullable();
            $table->string('customer_email')->nullable();
            $table->string('customer_phone')->nullable();
            $table->text('description')->nullable();

            // URLs
            $table->text('success_url');
            $table->text('failure_url')->nullable();
            $table->text('webhook_url')->nullable();

            // Extra data
            $table->json('metadata')->nullable();

            // Status lifecycle
            $table->enum('status', ['pending', 'success', 'failed', 'cancelled'])->default('pending');

            // Kashier integration
            $table->text('kashier_payment_url')->nullable();
            $table->string('kashier_transaction_id')->nullable();

            // Webhook back to merchant
            $table->timestamp('webhook_sent_at')->nullable();
            $table->text('webhook_response')->nullable();

            $table->timestamps();

            $table->index(['client_id', 'status']);
            $table->index('external_order_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('gateway_payments');
    }
};
