<?php

namespace App\Services;

class PortfolioData
{
    /**
     * Get all static portfolio projects.
     *
     * @return array<string, array>
     */
    public static function all(): array
    {
        return [
            'revflow' => [
                'slug' => 'revflow',
                'title_en' => 'RevFlow ERP & General Ledger Kernel',
                'title_ar' => 'محرك الحسابات والمبيعات المؤسسي RevFlow',
                'category' => 'ERP & Financials',
                'category_ar' => 'أنظمة الحسابات و ERP',
                'desc_en' => 'Enterprise double-entry accounting engine with automated journals, real-time balance sheets, ZATCA e-invoicing compliance, and multi-currency ledger reconciliation.',
                'desc_ar' => 'نظام مالي ومحاسبي مؤسسي متكامل بالقيود المزدوجة، يدعم الفوترة الإلكترونية، مراكز التكلفة، وإقفال الفترات المحاسبية لحظياً.',
                'img' => '/images/portfolio/revFlow.png',
                'techs' => ['Laravel 12', 'PostgreSQL', 'Livewire', 'TailwindCSS', 'Redis'],
                'live_url' => null,
                'metrics' => [
                    'Architecture' => 'Double-Entry General Ledger',
                    'Latency' => '< 8ms Journal Post',
                    'Reliability' => 'ACID DB Transactions',
                    'Compliance' => 'ZATCA Phase 2 Ready',
                ],
                'highlights_en' => [
                    'Real-time automated journal posting for all inventory movements and sales.',
                    'Multi-branch, multi-warehouse stock management with weighted average costing.',
                    'Dynamic income statement, cash flow statement, and balance sheet generation.',
                    'Granular role-based permissions with audit trails for every transaction.',
                ],
                'highlights_ar' => [
                    'توليد تلقائي لقيود اليومية لجميع حركات المخزون والمبيعات والسداد.',
                    'إدارة الفروع والمستودعات المتعددة بتقييم المخزون (متوسط التكلفة المرجح).',
                    'تقارير مالية فورية (قائمة الدخل، الميزانية العمومية، التدفقات النقدية).',
                    'سجل تدقيق شامل (Audit Trail) وصلاحيات دقيقة لكل مستخدم.',
                ],
            ],

            'chartcash' => [
                'slug' => 'chartcash',
                'title_en' => 'ChartCash Financial Analytics & BI Dashboard',
                'title_ar' => 'منصة التحليلات المالية ولوحات القيادة ChartCash',
                'category' => 'ERP & Financials',
                'category_ar' => 'أنظمة الحسابات و ERP',
                'desc_en' => 'High-velocity financial business intelligence platform providing real-time cash flow projections, customer acquisition cost KPIs, and interactive revenue visualization.',
                'desc_ar' => 'منصة ذكاء أعمال وتحليلات مالية متقدمة توفر مؤشرات التدفق النقدي، هوامش الربحية، وتوقعات الإيرادات التفاعلية.',
                'img' => '/images/portfolio/chartcash.png',
                'techs' => ['React', 'Inertia.js', 'Laravel', 'Chart.js', 'TailwindCSS'],
                'live_url' => null,
                'metrics' => [
                    'Processing' => 'Real-Time Aggregations',
                    'Dashboards' => 'Customizable BI Widgets',
                    'Visualization' => 'Interactive Canvas',
                    'Export' => 'PDF / Excel Reports',
                ],
                'highlights_en' => [
                    'Automated cash flow heatmaps and predictive burn-rate analytics.',
                    'Real-time webhook ingestion for payment gateways and e-commerce stores.',
                    'Dynamic customer lifetime value (LTV) and churn tracking.',
                    'Multi-tenant support with executive reporting export.',
                ],
                'highlights_ar' => [
                    'خرائط حرارية للتدفقات النقدية ومعدل حرق السيولة المالي.',
                    'استقبال وتجميع بيانات المبيعات عبر Webhooks من بوابات الدفع والمتاجر.',
                    'تتبع القيمة الدائمة للعميل (LTV) ومعدلات التسرب (Churn Rate).',
                    'تصدير تقارير تنفيذية عالية الجودة للإدارات وصناع القرار.',
                ],
            ],

            'trenz-whatscrm' => [
                'slug' => 'trenz-whatscrm',
                'title_en' => 'Trenz whatsCRM & WhatsApp Booking Platform',
                'title_ar' => 'منصة Trenz whatsCRM لإدارة المحادثات والحجوزات',
                'category' => 'SaaS & Cloud',
                'category_ar' => 'منصات سحابية SaaS',
                'desc_en' => 'Comprehensive WhatsApp Business automation suite featuring appointment booking, broadcast scheduling, multi-agent inbox, and Meta Graph API webhook pipelines.',
                'desc_ar' => 'منصة سحابية متكاملة لخدمة العملاء عبر واتساب، تدعم جدولة المواعيد، الإرسال الجماعي، وصندوق الوارد الموحد لفريق العمل.',
                'img' => '/images/portfolio/trenz-whatscrm.png',
                'techs' => ['Laravel', 'Vue/React', 'Meta Cloud API', 'WebSockets', 'MySQL'],
                'live_url' => null,
                'metrics' => [
                    'Throughput' => '100+ msgs / sec',
                    'Integration' => 'Official Meta Graph API',
                    'Agents' => 'Multi-agent Collaboration',
                    'Automations' => 'Smart Keyword Routing',
                ],
                'highlights_en' => [
                    'Official Meta Cloud API integration with automatic template approval syncing.',
                    'Appointment booking engine with automated reminder messages before consultations.',
                    'Multi-agent unified inbox with chat assignment, internal notes, and tagging.',
                    'Automated conversational chatbots with interactive buttons and list menus.',
                ],
                'highlights_ar' => [
                    'ربط رسمي مع Meta Cloud API ومزامنة قوالب الرسائل المعتمدة.',
                    'نظام متقدم لحجز المواعيد مع إرسال تذكيرات آلية قبل الموعد.',
                    'صندوق وارد موحد متعدد الوكلاء لتوزيع المحادثات وإضافة الملاحظات الداخلية.',
                    'روبوتات رد تفاعلية بالقوائم والأزرار للرد الفوري على استفسارات العملاء.',
                ],
            ],

            'kbdny' => [
                'slug' => 'kbdny',
                'title_en' => 'Kbdny Dropshipping & Multi-Vendor Ecosystem',
                'title_ar' => 'منصة كبدني (Kbdny) للتجارة والتسويق بالعمولة والدروب شيبنج',
                'category' => 'SaaS & Cloud',
                'category_ar' => 'منصات سحابية SaaS',
                'desc_en' => 'High-scale multi-tier dropshipping platform connecting suppliers, affiliate marketers, and logistics providers with automated commission payouts and bulk shipping manifests.',
                'desc_ar' => 'نظام تجارة إلكترونية ودروب شيبنج متكامل يربط الموردين والمسوقين وشركات الشحن، مع تتبع آلي للعمولات ومتابعة الشحنات.',
                'img' => '/images/portfolio/kbdny.png',
                'techs' => ['Laravel', 'Alpine.js', 'MySQL', 'Queue Workers', 'TailwindCSS'],
                'live_url' => null,
                'metrics' => [
                    'Volume' => '10k+ Orders / Month',
                    'Shipping' => 'B2B Courier Integration',
                    'Commissions' => 'Real-Time Wallet System',
                    'Inventory' => 'Multi-Vendor SKU Sync',
                ],
                'highlights_en' => [
                    'Multi-role portals for Affiliates, Suppliers, Warehouse Managers, and Admins.',
                    'Automated order state lifecycle: Confirmed, Dispatched, Partial Delivery, and Returned.',
                    'Bulk Excel manifest generation and tracking number sync for courier companies.',
                    'Affiliate digital wallet with automated commission calculation upon delivery.',
                ],
                'highlights_ar' => [
                    'بوابات مخصصة لكل من: المسوقين، التجار الموردين، مسؤولي المخازن، والإدارة.',
                    'دورة حياة ذكية للطلبات: تأكيد، شحن، تسليم جزئي، ومرتجع مع تحديثات فورية.',
                    'تصدير واستيراد كشوفات الشحن المجمعة ومزامنة بوالص الشحن.',
                    'محفظة مالية رقمية للمسوقين تحسب العمولات تلقائياً عند تأكيد التسليم.',
                ],
            ],

            'trenz-agency' => [
                'slug' => 'trenz-agency',
                'title_en' => 'Trenz Agency Digital Branding & Web Experience',
                'title_ar' => 'منصة وموقع وكالة Trenz للتسويق الرقمي والبرمجيات',
                'category' => 'Agency & Web',
                'category_ar' => 'مواقع ووكالات',
                'desc_en' => 'Modern high-converting web platform crafted for digital agencies, showcasing creative campaigns, interactive case studies, and automated lead discovery pipelines.',
                'desc_ar' => 'موقع تعريفي وتسويقي تفاعلي عالي الأداء مصمم لوكالات التسويق الرقمي لإبراز المشاريع وجذب العملاء المحتملين.',
                'img' => '/images/portfolio/trenz-agency.png',
                'techs' => ['Laravel', 'React', 'GSAP Animation', 'TailwindCSS'],
                'live_url' => null,
                'metrics' => [
                    'Speed' => '99/100 Google PageSpeed',
                    'Design' => 'Bespoke Dark Aesthetic',
                    'Interactions' => '60fps Micro-animations',
                    'Conversion' => 'Integrated Lead Funnel',
                ],
                'highlights_en' => [
                    'Ultra-fast server-rendered performance with dynamic fluid animations.',
                    'Portfolio showcases with full-screen media previews and technical breakdown.',
                    'Smart contact forms with instant notification routing via Telegram and WhatsApp.',
                    'Optimized typography and SEO architecture for dominant search ranking.',
                ],
                'highlights_ar' => [
                    'أداء فائق السرعة مع تأثيرات وحركات انسيابية بمعدل 60 إطاراً في الثانية.',
                    'معرض أعمال تفاعلي يعرض تفاصيل المشاريع والحلول التقنية المنفذة.',
                    'نماذج تواصل ذكية ترسل الإشعارات فوراً إلى قنوات تيليجرام وواتساب الإدارية.',
                    'بنية برمجية مهيأة بالكامل لمحركات البحث (SEO) وتجربة مستخدم متميزة.',
                ],
            ],

            'stock-manager' => [
                'slug' => 'stock-manager',
                'title_en' => 'StockManager Multi-Branch Inventory & POS',
                'title_ar' => 'نظام StockManager لإدارة المخزون ونقاط البيع المتعددة',
                'category' => 'ERP & Financials',
                'category_ar' => 'أنظمة الحسابات و ERP',
                'desc_en' => 'Industrial inventory management and Point of Sale solution built for retail and wholesale chains with barcode generation, reorder alert triggers, and offline resiliency.',
                'desc_ar' => 'نظام متكامل لإدارة المخازن ونقاط البيع للمحلات وسلاسل التوزيع، يدعم قراءة الباركود، التنبيه بنواقص الأصناف، والمبيعات السريعة.',
                'img' => '/images/portfolio/stockmanager.png',
                'techs' => ['Laravel', 'MySQL', 'Bootstrap', 'JavaScript', 'Barcode SDK'],
                'live_url' => null,
                'metrics' => [
                    'POS Speed' => '< 50ms Item Scan',
                    'Multi-Branch' => 'Real-Time Stock Transfers',
                    'Hardware' => 'ESC/POS Thermal Printers',
                    'Security' => 'Shift Balance Reconciliation',
                ],
                'highlights_en' => [
                    'Rapid keyboard-driven POS interface with instant barcode scanner support.',
                    'Inter-branch stock transfer requests with digital dispatch and receipt verification.',
                    'Automated low-stock threshold notifications and suggested purchase orders.',
                    'Cashier drawer opening, shift opening/closing, and daily variance reports.',
                ],
                'highlights_ar' => [
                    'واجهة كاشير ونقاط بيع فائقة السرعة تدعم اختصارات لوحة المفاتيح والباركود.',
                    'إدارة التحويلات المخزنية بين الفروع مع اعتمادات الاستلام والتسليم.',
                    'تنبيهات تلقائية بوصول المخزون لحد الطلب وتوليد أوامر الشراء.',
                    'إدارة أدراج النقدية، فتح وإغلاق الشيفتات، وتقارير العجز والزيادة اليومية.',
                ],
            ],

            'mini-fatora' => [
                'slug' => 'mini-fatora',
                'title_en' => 'Mini Fatora E-Invoicing & Billing SaaS',
                'title_ar' => 'منصة Mini Fatora للفوترة السريعة وإدارة الفواتير',
                'category' => 'SaaS & Cloud',
                'category_ar' => 'منصات سحابية SaaS',
                'desc_en' => 'Lightweight, rapid billing platform for freelancers and service agencies to issue branded PDF invoices, track payment status, and accept online transactions.',
                'desc_ar' => 'منصة فوترة سحابية خفيفة وسريعة للمستقلين والشركات الناشئة لإصدار فواتير احترافية ومتابعة تحصيل المدفوعات.',
                'img' => '/images/portfolio/minifatora.png',
                'techs' => ['Laravel', 'Vue.js', 'DomPDF', 'MySQL', 'TailwindCSS'],
                'live_url' => null,
                'metrics' => [
                    'Generation' => 'Instant PDF Rendering',
                    'Sharing' => 'One-Click WhatsApp / Email',
                    'Currencies' => 'Multi-Currency Support',
                    'Reminders' => 'Automated Due Date Alerts',
                ],
                'highlights_en' => [
                    'Customizable invoice templates with brand logo, terms, and tax QR codes.',
                    'Client payment portal with online card and wallet checkout integration.',
                    'Automatic payment reminder dispatch via email and WhatsApp upon overdue dates.',
                    'Comprehensive income analytics, recurring subscriptions, and tax summaries.',
                ],
                'highlights_ar' => [
                    'قوالب فواتير قابلة للتخصيص بالهوية والشعار ورموز الاستجابة السريعة (QR).',
                    'بوابة دفع مخصصة للعميل لسداد الفواتير عبر البطاقات والمحافظ الإلكترونية.',
                    'إرسال تذكيرات دفع تلقائية عند اقتراب أو تأخر موعد السداد.',
                    'تحليلات شاملة للمقبوضات، الفواتير المتكررة، وملخصات الضرائب الدورية.',
                ],
            ],

            'vodafone-crm' => [
                'slug' => 'vodafone-crm',
                'title_en' => 'Vodafone Distribution Operations & CRM',
                'title_ar' => 'نظام إدارة الموزعين والعمليات الميدانية لـ Vodafone',
                'category' => 'ERP & Financials',
                'category_ar' => 'أنظمة الحسابات و ERP',
                'desc_en' => 'Mission-critical enterprise CRM developed for a primary telecom distributor, handling thousands of line activations, scratch card serial tracking, and representative commissions.',
                'desc_ar' => 'نظام مؤسسي متقدم لإدارة شبكة الموزعين والمناديب الميدانيين لخدمات الاتصالات، تتبع شرائح الخطوط، وحساب العمولات.',
                'img' => '/images/portfolio/vodafone-crm.jpg',
                'techs' => ['Laravel', 'PostgreSQL', 'Livewire', 'Excel Engine', 'Redis'],
                'live_url' => null,
                'metrics' => [
                    'Scale' => '50k+ SIM Serial Records',
                    'Representatives' => 'GPS & Route Tracking',
                    'Reconciliation' => 'End-of-Day Balance Audit',
                    'Security' => 'Role-Based Operational Access',
                ],
                'highlights_en' => [
                    'Comprehensive serial number lifecycle tracking from central warehouse to retail shops.',
                    'Representative route planning, cash collection verification, and daily targets.',
                    'Dynamic tiered commission calculation based on activated line volume and packages.',
                    'Real-time discrepancy detection between warehouse dispatches and collected balances.',
                ],
                'highlights_ar' => [
                    'تتبع دقيق لحركة الأرقام التسلسلية من المستودع الرئيسي حتى وصولها للمحلات.',
                    'إدارة خطوط سير المناديب، استلام العهد النقدية، ومتابعة الأهداف البيعية.',
                    'حساب عمولات المناديب والموزعين آلياً بناءً على الشرائح وحجم المبيعات.',
                    'مطابقة فورية لمنع أي فروقات بين البضائع المسلمة والنقدية المحصلة.',
                ],
            ],

            'amc-academy' => [
                'slug' => 'amc-academy',
                'title_en' => 'AMC Academy E-Learning & Video Streaming Platform',
                'title_ar' => 'منصة AMC Academy للتعليم والتدريب الرقمي المشفر',
                'category' => 'SaaS & Cloud',
                'category_ar' => 'منصات سحابية SaaS',
                'desc_en' => 'Scalable learning management system with DRM-protected video delivery, dynamic watermarking, interactive quizzes, student progress tracking, and certificate issuance.',
                'desc_ar' => 'منصة تعليمية متكاملة تدعم حماية الفيديو من التسجيل، العلامات المائية الديناميكية، الاختبارات التفاعلية، وإصدار الشهادات.',
                'img' => '/images/portfolio/amcacademy.jpg',
                'techs' => ['Laravel', 'React', 'Video.js', 'FFmpeg', 'MySQL'],
                'live_url' => null,
                'metrics' => [
                    'Protection' => 'Dynamic User Watermarking',
                    'Streaming' => 'HLS Adaptive Bitrate',
                    'Assessment' => 'Automated Quiz Grading',
                    'Engagement' => 'Student Progress Analytics',
                ],
                'highlights_en' => [
                    'Anti-piracy dynamic screen watermarks displaying student IP and phone number.',
                    'HLS adaptive video encoding for seamless playback on low-bandwidth networks.',
                    'Automated grading engine with timed exam constraints and randomized question banks.',
                    'Certificate generation with verifiable cryptographic QR validation codes.',
                ],
                'highlights_ar' => [
                    'حماية متقدمة ضد تسريب المحتوى بعلامات مائية تظهر بيانات الطالب لحظياً.',
                    'بث فيديو تكيفي (HLS) يعمل بكفاءة عالية حتى مع سرعات الإنترنت الضعيفة.',
                    'نظام اختبارات ذكي بالتصحيح التلقائي وتحديد أوقات الإجابة وبنوك الأسئلة.',
                    'إصدار شهادات إتمام الدورات مع رمز استجابة سريعة (QR) للتحقق من المصداقية.',
                ],
            ],

            'project-manager' => [
                'slug' => 'project-manager',
                'title_en' => 'Enterprise Project & Agile Task Manager',
                'title_ar' => 'منصة إدارة المشاريع والمهام الهندسية Project Manager',
                'category' => 'SaaS & Cloud',
                'category_ar' => 'منصات سحابية SaaS',
                'desc_en' => 'Collaborative engineering workspace featuring Kanban boards, Gantt timelines, live time-tracking counters, milestone deliverables, and automated client status reporting.',
                'desc_ar' => 'بيئة عمل متكاملة لإدارة المشاريع البرمجية والهندسية، تدعم لوحات كانبان، الجداول الزمنية، وحساب ساعات العمل بدقة.',
                'img' => '/images/portfolio/projectmanager.png',
                'techs' => ['Laravel', 'React', 'TypeScript', 'TailwindCSS', 'MySQL'],
                'live_url' => null,
                'metrics' => [
                    'Tracking' => 'Sub-second Timers',
                    'Views' => 'Kanban, List, Gantt, Calendar',
                    'Collaboration' => 'Real-time Task Updates',
                    'Reporting' => 'Automated Client Portals',
                ],
                'highlights_en' => [
                    'Interactive drag-and-drop Kanban boards with custom status pipelines and priority filters.',
                    'Integrated stopwatch timer recording billable hours and generating direct client invoices.',
                    'Granular milestone progress bars and task dependency relationship mapping.',
                    'Secure client view portal allowing stakeholders to monitor project velocity in real-time.',
                ],
                'highlights_ar' => [
                    'لوحات كانبان تفاعلية بالسحب والإفلات مع تخصيص مراحل العمل والأولويات.',
                    'مؤقتات زمنية مدمجة لتسجيل ساعات العمل القابلة للفوترة وإصدار فواتيرها.',
                    'تتبع نسب إنجاز المعالم الرئيسية وربط المهام بتبعيات التنفيذ.',
                    'بوابة وصول آمنة للعملاء لمتابعة سير تنفيذ مشاريعهم بشفافية واحترافية.',
                ],
            ],

            'telecom-system' => [
                'slug' => 'telecom-system',
                'title_en' => 'B2B Telecom & ISP Automated Recharge Engine',
                'title_ar' => 'بوابة شحن وإدارة خدمات الاتصالات والإنترنت B2B',
                'category' => 'SaaS & Cloud',
                'category_ar' => 'منصات سحابية SaaS',
                'desc_en' => 'High-throughput telecom gateway communicating with ISP APIs to execute instant automated bill recharges, bundle activations, and quota monitoring for enterprise clients.',
                'desc_ar' => 'منصة خدمات الاتصالات والشحن الفوري للشركات، متصلة بواجهات مزودي الإنترنت والاتصالات لمعالجة المدفوعات والاشتراكات.',
                'img' => '/images/portfolio/telecom-system.png',
                'techs' => ['Laravel', 'RabbitMQ', 'Redis', 'REST APIs', 'PostgreSQL'],
                'live_url' => null,
                'metrics' => [
                    'Execution' => '< 1.2s API Response',
                    'Reliability' => '99.98% Gateway Uptime',
                    'Concurrency' => 'Bulk Batch Requests',
                    'Security' => 'Encrypted Token Handshake',
                ],
                'highlights_en' => [
                    'Direct asynchronous API connectors to top internet service providers and telecoms.',
                    'Automated retry and fallback routing for transient carrier timeouts.',
                    'B2B merchant wallet architecture with pre-funded balances and credit limits.',
                    'Detailed transactional log auditing with raw payload inspection for debugging.',
                ],
                'highlights_ar' => [
                    'ربط مباشر بواجهات مزودي خدمات الإنترنت والاتصالات لتنفيذ العمليات فوراً.',
                    'نظام ذكي لإعادة المحاولة والتحويل التلقائي في حال انقطاع أي مزود.',
                    'محافظ مالية مسبقة الدفع للتجار مع إدارة حدود الائتمان وسجلات العمليات.',
                    'سجل عمليات مفصل يتيح فحص البيانات التقنية لضمان دقة المعاملات.',
                ],
            ],

            'altayaraa' => [
                'slug' => 'altayaraa',
                'title_en' => 'Altayaraa High-Traffic E-Commerce Platform',
                'title_ar' => 'منصة التجارة الإلكترونية السريعة الطيارة (Altayaraa)',
                'category' => 'E-Commerce & Mobile',
                'category_ar' => 'متاجر وتطبيقات الموبايل',
                'desc_en' => 'Fast e-commerce storefront engineered for viral social media campaigns, featuring 1-click cash-on-delivery checkout, abandoned cart recovery, and warehouse integration.',
                'desc_ar' => 'متجر إلكتروني فائق السرعة مصمم للحملات الإعلانية المكثفة، يدعم الشراء السريع بنقرة واحدة (COD) ومزامنة المخازن.',
                'img' => '/images/portfolio/altayaraa.png',
                'techs' => ['Laravel', 'Alpine.js', 'MySQL', 'TailwindCSS', 'Redis'],
                'live_url' => null,
                'metrics' => [
                    'Checkout' => 'Single-Page COD Funnel',
                    'Conversion' => '+34% Boost over standard carts',
                    'Load Time' => 'Sub-800ms First Contentful Paint',
                    'Mobile' => '100% Touch-Optimized',
                ],
                'highlights_en' => [
                    'Frictionless 1-page checkout without mandatory account registration.',
                    'Automated SMS & WhatsApp verification triggers to reduce fake order rates.',
                    'Dynamic upsell and cross-sell quantity discounts right on the product page.',
                    'Direct automated syncing with fulfillment centers and shipping couriers.',
                ],
                'highlights_ar' => [
                    'شراء فوري من صفحة واحدة دون اشتراط إنشاء حساب لرفع نسبة التحويل.',
                    'تأكيد الطلبات تلقائياً عبر الرسائل النصية وواتساب لتقليل نسبة المرتجعات.',
                    'عروض بيع إضافية (Upsells) وخصومات كميات تفاعلية في صفحة المنتج.',
                    'ربط مباشر مع غرف التعبئة وشركات الشحن لإصدار البوالص آلياً.',
                ],
            ],

            'forex-app' => [
                'slug' => 'forex-app',
                'title_en' => 'Forex Signal & Algorithmic Trading Mobile Companion',
                'title_ar' => 'تطبيق إشارات التداول وتحليل أسواق العملات Forex App',
                'category' => 'E-Commerce & Mobile',
                'category_ar' => 'متاجر وتطبيقات الموبايل',
                'desc_en' => 'Real-time financial trading companion delivering sub-second market alerts, technical indicator overlays, and algorithmic copy-trade notifications to traders globally.',
                'desc_ar' => 'تطبيق موبايل مالي متخصص في إرسال إشارات التداول اللحظية، تحليلات المؤشرات الفنية، وتنبيهات فرص السوق.',
                'img' => '/images/portfolio/forex-app.png',
                'techs' => ['Flutter', 'Node.js', 'WebSockets', 'TradingView API', 'Redis'],
                'live_url' => null,
                'metrics' => [
                    'Alert Speed' => '< 150ms Push Notification',
                    'Feeds' => 'Live MT4 / MT5 Integration',
                    'Charts' => 'Embedded Interactive Canvas',
                    'Security' => 'Biometric Authentication',
                ],
                'highlights_en' => [
                    'Ultra-low-latency push notifications with exact Entry, Take-Profit, and Stop-Loss levels.',
                    'Live chart integrations with custom technical indicator overlays (RSI, MACD, Bollinger).',
                    'Historical signal performance tracker with transparent win-rate metrics.',
                    'Subscription tier gating powered by in-app purchases and digital wallet tokens.',
                ],
                'highlights_ar' => [
                    'إشعارات فورية سريعة بنقاط الدخول وجني الأرباح ووقف الخسارة بدقة.',
                    'رسوم بيانية حية مع مؤشرات التحليل الفني المتقدمة لتسهيل اتخاذ القرار.',
                    'سجل شفاف لنتائج الإشارات السابقة ونسب نجاح الصفقات التاريخية.',
                    'نظام اشتراكات وباقات متميزة مع بوابات دفع آمنة.',
                ],
            ],

            'forex-bot' => [
                'slug' => 'forex-bot',
                'title_en' => 'Autonomous Forex Algorithmic Trading Bot',
                'title_ar' => 'روبوت التداول الخوارزمي الآلي Forex Bot',
                'category' => 'AI & Bots',
                'category_ar' => 'الذكاء الاصطناعي والروبوتات',
                'desc_en' => 'Automated execution bot connecting to MetaTrader APIs, implementing quantitative risk management models, trailing stop mechanics, and multi-currency hedge strategies.',
                'desc_ar' => 'محرك تداول آلي خوارزمي متصل بمنصات التداول لتنفيذ الصفقات وفق قواعد إدارة المخاطر واستراتيجيات التحوط المالي.',
                'img' => '/images/portfolio/forex.png',
                'techs' => ['Python', 'MQL5', 'MetaTrader API', 'ZeroMQ', 'Docker'],
                'live_url' => null,
                'metrics' => [
                    'Execution' => '< 15ms Latency',
                    'Risk Engine' => 'Max Drawdown Enforcement',
                    'Uptime' => '24/7 VPS Containerized',
                    'Logging' => 'Encrypted Trade Journal',
                ],
                'highlights_en' => [
                    'Strict quantitative position sizing based on account equity and dynamic volatility.',
                    'Dynamic trailing stop loss and partial take-profit automation during high-impact news.',
                    'Multi-pair correlation matrix avoiding overexposure to correlated currency baskets.',
                    'Instant Telegram and Discord execution alerts with trade rationale logs.',
                ],
                'highlights_ar' => [
                    'تحديد دقيق لحجم اللوت والصفقات بناءً على حجم رأس المال والتقلبات.',
                    'وقف خسارة متحرك (Trailing Stop) وجني أرباح جزئي آلي عند تحقيق الأهداف.',
                    'مصفوفة قياس ارتباط أزواج العملات لمنع المخاطر التراكمية.',
                    'إشعارات فورية عبر تيليجرام وديسكورد بكل العمليات والصفقات المنفذة.',
                ],
            ],

            'amc-social' => [
                'slug' => 'amc-social',
                'title_en' => 'AMC Social Multi-Platform Publishing Cloud',
                'title_ar' => 'منصة النشر والتسويق الاجتماعي الموحد AMC Social',
                'category' => 'SaaS & Cloud',
                'category_ar' => 'منصات سحابية SaaS',
                'desc_en' => 'Centralized social media scheduler and engagement analytics hub enabling brands to schedule posts across Facebook, Instagram, LinkedIn, and X simultaneously.',
                'desc_ar' => 'منصة سحابية لإدارة وجدولة المنشورات والتفاعل على شبكات التواصل الاجتماعي (فيسبوك، انستجرام، لينكد إن، إكس) من مكان واحد.',
                'img' => '/images/portfolio/amcsocial.png',
                'techs' => ['Laravel', 'Vue.js', 'Meta Graph API', 'LinkedIn API', 'Redis Queue'],
                'live_url' => null,
                'metrics' => [
                    'Publishing' => 'Scheduled Multi-Channel Queue',
                    'Analytics' => 'Audience Growth & Engagement',
                    'Asset Library' => 'Integrated Media Editor',
                    'Collaboration' => 'Team Post Approval Flow',
                ],
                'highlights_en' => [
                    'Unified content calendar with visual drag-and-drop scheduling across all networks.',
                    'Integrated image cropper and video validator tailored for each platform specs.',
                    'Role-based workflow allowing copywriters to submit drafts for client approval.',
                    'Consolidated social analytics reporting follower growth and top-performing posts.',
                ],
                'highlights_ar' => [
                    'جدول محتوى موحد بالسحب والإفلات للنشر المجدول على كافة المنصات.',
                    'محرر وسائط مدمج يضبط أبعاد الصور والفيديوهات تلقائياً لكل منصة.',
                    'دورة موافقات برمجية تتيح لصناع المحتوى إرسال المسودات للمراجعة والاعتماد.',
                    'تقارير تفاعلية مجمعة تقيس نمو المتابعين وتفاعل الجمهور مع المنشورات.',
                ],
            ],

            'nokhpa' => [
                'slug' => 'nokhpa',
                'title_en' => 'Nokhpa Premium E-Commerce Mobile App',
                'title_ar' => 'تطبيق النخبة (Nokhpa) للتجارة الإلكترونية والتسوق الفاخر',
                'category' => 'E-Commerce & Mobile',
                'category_ar' => 'متاجر وتطبيقات الموبايل',
                'desc_en' => 'Luxury retail mobile shopping application featuring curated product lookbooks, personalized recommendations, Apple Pay integration, and live GPS order tracking.',
                'desc_ar' => 'تطبيق تسوق إلكتروني متطور للمنتجات الفاخرة، يدعم Apple Pay، تتبع مسار المندوب بالـ GPS، وتجربة مستخدم راقية.',
                'img' => '/images/portfolio/nokhpa.png',
                'techs' => ['Flutter', 'Laravel REST API', 'Apple Pay', 'Google Maps API', 'MySQL'],
                'live_url' => null,
                'metrics' => [
                    'Design' => 'High-Fashion Minimal Aesthetic',
                    'Checkout' => 'Apple Pay & Card Gateways',
                    'Tracking' => 'Live Courier Geolocation',
                    'Notifications' => 'Rich Media Push Alerts',
                ],
                'highlights_en' => [
                    'Seamless native checkout with Apple Pay, credit cards, and installment plans (Tabby/Tamara).',
                    'Interactive product storytelling with high-resolution image galleries and size guides.',
                    'Real-time delivery driver tracking on interactive vector maps.',
                    'Smart customer loyalty club rewarding repeated purchases with discount points.',
                ],
                'highlights_ar' => [
                    'دفع فوري متكامل مع Apple Pay والبطاقات البنكية وأنظمة التقسيط.',
                    'عرض بصري فائق الدقة للمنتجات مع تفاصيل المقاسات والمواصفات.',
                    'تتبع حي لموقع مندوب التوصيل على الخريطة التفاعلية حتى باب المنزل.',
                    'نظام ولاء ومكافآت ذكي يمنح نقاطاً وخصومات عند كل عملية شراء.',
                ],
            ],

            'duplicate-finder' => [
                'slug' => 'duplicate-finder',
                'title_en' => 'Duplicate Finder High-Speed Desktop Utility',
                'title_ar' => 'أداة Duplicate Finder للبحث وفحص الملفات المكررة',
                'category' => 'Desktop & Automation',
                'category_ar' => 'برامج سطح المكتب والأتمتة',
                'desc_en' => 'Native Windows desktop application utilizing multi-threaded SHA-256 block hashing to scan terabytes of storage and eliminate duplicate files safely in seconds.',
                'desc_ar' => 'برنامج ويندوز مكتبي فائق السرعة يعتمد على خوارزميات التشفير لفحص مساحات التخزين الضخمة واكتشاف الملفات المكررة بدقة.',
                'img' => '/images/portfolio/duplicate-finder.jpg',
                'techs' => ['C#', '.NET Core', 'WPF', 'Multi-Threading', 'Win32 API'],
                'live_url' => null,
                'metrics' => [
                    'Scan Rate' => '10,000+ Files / Second',
                    'Accuracy' => '100% Bitwise SHA Verification',
                    'Memory Footprint' => '< 45MB RAM Usage',
                    'Safety' => 'Recycle Bin Integration',
                ],
                'highlights_en' => [
                    'Multi-staged scanning pipeline: Size Filter -> Header Check -> Full Hash.',
                    'Parallel multi-core processing scanning massive NAS and local SSD drives effortlessly.',
                    'Visual duplicate inspection with inline image, video, and audio previews.',
                    'Safe cleanup options with direct Recycle Bin routing or symbolic link creation.',
                ],
                'highlights_ar' => [
                    'فحص متعدد المراحل (الحجم -> ترويسة الملف -> التشفير الكامل) لسرعة قصوى.',
                    'استغلال كامل لكافة أنوية المعالج للتعامل مع محركات الأقراص العملاقة.',
                    'معاينة بصرية فورية للصور ومقاطع الفيديو والملفات الصوتية المكررة.',
                    'خيارات حذف آمنة مع دعم سلة المهملات وإنشاء الروابط الرمزية.',
                ],
            ],

            'map-extractor' => [
                'slug' => 'map-extractor',
                'title_en' => 'Map Extractor B2B Lead Generation Studio',
                'title_ar' => 'برنامج استخراج بيانات الأنشطة والشركات Map Extractor',
                'category' => 'Desktop & Automation',
                'category_ar' => 'برامج سطح المكتب والأتمتة',
                'desc_en' => 'High-performance desktop crawler extracting verified business leads (names, phone numbers, websites, GPS coordinates) from Google Maps with zero proxy bans.',
                'desc_ar' => 'أداة سطح مكتب قوية لاستخراج بيانات الشركات والأنشطة التجارية من خرائط جوجل مع تصنيف أرقام الهواتف وتصديرها لإكسيل.',
                'img' => '/images/portfolio/map-extractor.jpg',
                'techs' => ['C#', '.NET Core', 'Chromium Embedded', 'Excel Interop', 'SQLite'],
                'live_url' => null,
                'metrics' => [
                    'Speed' => '2,500+ Leads / Hour',
                    'Data Points' => 'Phone, Website, Email, Reviews, Rating',
                    'Export' => 'XLSX, CSV, VCF (Phonebook)',
                    'Bypass' => 'Anti-Bot Fingerprint Spoofing',
                ],
                'highlights_en' => [
                    'Deep geographical grid scanning covering specified cities, districts, and categories.',
                    'Automated website scraper following business URLs to discover contact emails and socials.',
                    'Direct export to VCF phonebook files ready for instant mobile contact importing.',
                    'Built-in duplicate filtering ensuring unique phone numbers across campaign runs.',
                ],
                'highlights_ar' => [
                    'فحص جغرافي دقيق يغطي مدن ومناطق وتصنيفات تجارية محددة.',
                    'مستكشف آلي يزور مواقع الشركات المستخرجة لجلب البريد الإلكتروني وروابط التواصل.',
                    'تصدير مباشر لملفات جهات الاتصال (VCF) لحفظ الأرقام في الهاتف بضغطة واحدة.',
                    'فلترة تلقائية تمنع تكرار أي رقم هاتف أو شركة في ملفات الإكسيل الناتجة.',
                ],
            ],

            'whatsapp-sender' => [
                'slug' => 'whatsapp-sender',
                'title_en' => 'WhatsApp Sender Enterprise Bulk Automation',
                'title_ar' => 'برنامج الإرسال والتسويق الجماعي عبر واتساب WhatsApp Sender',
                'category' => 'Desktop & Automation',
                'category_ar' => 'برامج سطح المكتب والأتمتة',
                'desc_en' => 'Desktop marketing engine designed to dispatch personalized customer notifications and marketing media with automated delay controls and number verification.',
                'desc_ar' => 'برنامج سطح مكتب لأتمتة إرسال رسائل التنبيهات والإعلانات عبر واتساب مع التحكم في فترات التأخير لحماية الأرقام.',
                'img' => '/images/portfolio/whatsapp-sender.png',
                'techs' => ['C#', 'Selenium Core', 'Chromium Driver', 'SQLite', 'WPF'],
                'live_url' => null,
                'metrics' => [
                    'Personalization' => 'Dynamic {{Name}} Tags',
                    'Safety' => 'Human-Like Random Delay Engine',
                    'Attachments' => 'PDFs, Images, Videos, Audio',
                    'Filter' => 'WhatsApp Number Validator',
                ],
                'highlights_en' => [
                    'Smart random delay engine imitating human typing cadence to preserve account safety.',
                    'Dynamic message variables pulling customized client data directly from Excel sheets.',
                    'Integrated filter scanning contact lists to verify WhatsApp registration prior to broadcast.',
                    'Multi-account rotation alternating between numbers during large notification campaigns.',
                ],
                'highlights_ar' => [
                    'نظام محاكاة الكتابة البشرية وفواصل زمنية متغيرة لحماية الحسابات.',
                    'دعم المتغيرات المخصصة لجلب أسماء وتفاصيل الفواتير من ملف الإكسيل لكل عميل.',
                    'فاحص مدمج للتحقق من وجود الحساب على واتساب قبل بدء الإرسال.',
                    'دعم التبديل بين عدة حسابات وأرقام بالتناوب خلال الحملات الإعلانية الكبيرة.',
                ],
            ],

            'telegram-sender' => [
                'slug' => 'telegram-sender',
                'title_en' => 'Telegram Sender Channel & Community Broadcaster',
                'title_ar' => 'برنامج النشر والإرسال التلقائي في تيليجرام Telegram Sender',
                'category' => 'Desktop & Automation',
                'category_ar' => 'برامج سطح المكتب والأتمتة',
                'desc_en' => 'High-speed broadcast tool utilizing native MTProto APIs to deliver announcements, signals, and media across thousands of Telegram groups and channels simultaneously.',
                'desc_ar' => 'أداة سطح مكتب فائقة السرعة تستخدم بروتوكول MTProto لنشر الإعلانات والإشارات والتحديثات في قنوات ومجموعات تيليجرام.',
                'img' => '/images/portfolio/telegram-sender.png',
                'techs' => ['C#', 'TDLib / WTelegramClient', 'SQLite', '.NET Core'],
                'live_url' => null,
                'metrics' => [
                    'Speed' => 'Native MTProto Sub-second Dispatch',
                    'Multi-Session' => 'Unlimited Account Switching',
                    'Targeting' => 'Groups, Channels, and Direct Users',
                    'Scheduler' => 'Time-based Automated Queue',
                ],
                'highlights_en' => [
                    'Native Telegram MTProto integration ensuring maximum transmission speed and reliability.',
                    'Multi-session manager maintaining multiple logged-in accounts safely without re-auth.',
                    'Group member scraper extracting active discussion participants into targeted broadcast lists.',
                    'Automated message scheduling with rich formatting, inline buttons, and pinned messages.',
                ],
                'highlights_ar' => [
                    'ربط مباشر ببروتوكول MTProto لسرعة إرسال قياسية واستقرار تام.',
                    'إدارة جلسات متعددة تتيح تشغيل عدة حسابات بأمان ودون الحاجة لتسجيل الدخول المتكرر.',
                    'استخراج أعضاء المجموعات النشطين لإنشاء قوائم استهداف مهتمة.',
                    'جدولة النشر التلقائي مع دعم الأزرار الشفافة وتنسيقات النصوص الغنية وتثبيت الرسائل.',
                ],
            ],

            'email-sender' => [
                'slug' => 'email-sender',
                'title_en' => 'High-Deliverability Email Campaign Platform',
                'title_ar' => 'منصة الحملات البريدية والتسليم العالي Email Sender',
                'category' => 'SaaS & Cloud',
                'category_ar' => 'منصات سحابية SaaS',
                'desc_en' => 'Enterprise email dispatch engine engineered for 99%+ inbox placement, featuring dynamic SMTP pool rotation, DKIM/SPF verification, and real-time open/click telemetry.',
                'desc_ar' => 'منصة سحابية متقدمة لإرسال وإدارة النشرات البريدية مع تدوير خوادم الـ SMTP والتحقق من التوقيع الرقمي لمنع مجلد السبام.',
                'img' => '/images/portfolio/emailsender.png',
                'techs' => ['Laravel', 'PostgreSQL', 'Redis Queue', 'Amazon SES / SendGrid', 'TailwindCSS'],
                'live_url' => null,
                'metrics' => [
                    'Capacity' => '500k+ Emails / Day',
                    'Deliverability' => 'Automated SMTP IP Rotation',
                    'Telemetry' => 'Zero-Pixel Open & Click Tracking',
                    'Compliance' => '1-Click Unsubscribe Handling',
                ],
                'highlights_en' => [
                    'Smart IP and SMTP server pool rotation preventing blacklisting during large volume sends.',
                    'Real-time bounce handler automatically pruning invalid and risky email addresses.',
                    'Visual drag-and-drop HTML email builder with responsive cross-client previews.',
                    'Deep campaign analytics reporting open rates, click-through rates, and geolocation data.',
                ],
                'highlights_ar' => [
                    'تدوير ذكي لخوادم وعناوين الـ IP لمنع الحظر وضمان وصول الرسائل لصندوق الوارد الرئيسي.',
                    'معالجة آلية للرسائل المرتدة (Bounces) لتنظيف القوائم البريدية تلقائياً.',
                    'محرر رسائل تفاعلي مع معاينة دقيقة على مختلف أجهزة وتطبيقات البريد.',
                    'تحليلات فورية تقيس معدل فتح الرسائل، النقر على الروابط، والمواقع الجغرافية.',
                ],
            ],

            'inbox-sender' => [
                'slug' => 'inbox-sender',
                'title_en' => 'Inbox Sender Desktop Warmup & Delivery Tool',
                'title_ar' => 'برنامج تسخين الخوادم وإرسال البريد المباشر Inbox Sender',
                'category' => 'Desktop & Automation',
                'category_ar' => 'برامج سطح المكتب والأتمتة',
                'desc_en' => 'Desktop application designed for transactional email warmup, multi-threaded SMTP testing, and targeted corporate outreach with customized header fingerprints.',
                'desc_ar' => 'أداة سطح مكتب لتسخين خوادم البريد الإلكتروني، فحص السيرفرات، وإرسال الرسائل الموجهة بأعلى موثوقية.',
                'img' => '/images/portfolio/inbox-sender.png',
                'techs' => ['C#', '.NET Core', 'MailKit', 'MimeKit', 'SQLite'],
                'live_url' => null,
                'metrics' => [
                    'Throughput' => 'Multi-threaded SMTP Engine',
                    'Warmup' => 'Gradual Ramp-Up Scheduling',
                    'Testing' => 'Spam Score & DNS Pre-flight Check',
                    'Security' => 'TLS 1.3 / SSL Encryption',
                ],
                'highlights_en' => [
                    'Automated gradual warmup schedules training spam filters to recognize new domains as safe.',
                    'Comprehensive DNS diagnostic verifying SPF, DKIM, DMARC, and MX records before sending.',
                    'Spam trigger word analyzer warning users about dangerous promotional copy.',
                    'Threaded sending queue distributing emails across multiple authenticated accounts.',
                ],
                'highlights_ar' => [
                    'جدولة تدريجية لتسخين الدومينات الجديدة لبناء سمعة ممتازة لدى مزودي البريد.',
                    'فحص شامل لإعدادات الـ DNS (SPF, DKIM, DMARC) قبل بدء الإرسال لضمان الأمان.',
                    'محلل ذكي يفحص نصوص الرسائل وينبه المستخدم عند وجود كلمات قد تسبب الحظر.',
                    'توزيع الحمل على خيوط معالجة متعددة لتسريع وتيرة الإرسال دون إجهاد السيرفر.',
                ],
            ],

            'heic-converter' => [
                'slug' => 'heic-converter',
                'title_en' => 'HEIC to JPG/PNG Batch Converter Utility',
                'title_ar' => 'أداة تحويل صور الآيفون HEIC Converter فائقة السرعة',
                'category' => 'Desktop & Automation',
                'category_ar' => 'برامج سطح المكتب والأتمتة',
                'desc_en' => 'Lightweight Windows utility allowing photographers and agencies to convert thousands of Apple HEIC photos into JPG/PNG formats instantly while preserving EXIF metadata.',
                'desc_ar' => 'برنامج ويندوز خفيف وسريع لتحويل صور آبل (HEIC) إلى صيغ JPG و PNG بدفعة واحدة مع الحفاظ الكامل على الجودة وبيانات EXIF.',
                'img' => '/images/portfolio/heic-converter.png',
                'techs' => ['C#', 'ImageMagick Native', 'WPF', '.NET Core'],
                'live_url' => null,
                'metrics' => [
                    'Speed' => '100+ Photos / Minute',
                    'Metadata' => 'Full EXIF & GPS Preservation',
                    'Interface' => 'Drag-and-Drop Batch Queue',
                    'Quality' => 'Lossless Compression Engine',
                ],
                'highlights_en' => [
                    'Drag-and-drop entire folders of HEIC images for simultaneous conversion.',
                    'Preserves original camera metadata including capture date, exposure, and GPS location.',
                    'Configurable JPEG quality slider balancing file size against crisp visual clarity.',
                    'Offline zero-cloud processing guaranteeing total user privacy.',
                ],
                'highlights_ar' => [
                    'سحب وإفلات مجلدات كاملة من الصور لتحويلها جميعاً بضغطة زر.',
                    'الحفاظ على البيانات الوصفية للكاميرا (تاريخ الالتقاط، إعدادات العدسة، والموقع الجغرافي).',
                    'التحكم في درجة ضغط وجودة الصورة للموازنة بين الحجم ودقة التفاصيل.',
                    'معالجة محلية 100% بدون إنترنت لضمان الخصوصية التامة لصور المستخدم.',
                ],
            ],

            'text-studio' => [
                'slug' => 'text-studio',
                'title_en' => 'Studio Text Advanced Regex & Data Processing',
                'title_ar' => 'بيئة معالجة النصوص والبيانات الضخمة Studio Text',
                'category' => 'Desktop & Automation',
                'category_ar' => 'برامج سطح المكتب والأتمتة',
                'desc_en' => 'Engineered desktop text studio providing massive file editing, regular expression batch replacement, deduplication, and automated data structuring pipelines.',
                'desc_ar' => 'بيئة عمل مكتبية متطورة لمعالجة النصوص والقوائم الضخمة، تطبيق خوارزميات Regex، وإعادة هيكلة البيانات.',
                'img' => '/images/portfolio/text-studio.jpg',
                'techs' => ['C#', '.NET Core', 'Avalonia / WPF', 'Regex Engine'],
                'live_url' => null,
                'metrics' => [
                    'Capacity' => 'Opens 2GB+ Plaintext Files Instantly',
                    'Operations' => 'Regex, Split, Merge, Dedupe, Sort',
                    'Performance' => 'Zero-lag Virtualized Scrolling',
                    'Automation' => 'Macro Scripting Pipelines',
                ],
                'highlights_en' => [
                    'Virtualized memory architecture rendering gigabyte-sized log files without freezing.',
                    'Advanced regular expression testbed with live pattern matching and highlight preview.',
                    'One-click data sanitation: remove empty lines, trim whitespace, and sort alphabetically.',
                    'Reusable processing macro pipelines automating multi-step text transformation tasks.',
                ],
                'highlights_ar' => [
                    'بنية ذاكرة افتراضية تفتح ملفات السجلات والبيانات الضخمة (2GB+) دون أي بطء.',
                    'مختبر مدمج للتعابير النمطية (Regex) مع معاينة فورية لنتائج الاستبدال.',
                    'تنظيف وتنسيق فوري للقوائم: إزالة الأسطر الفارغة، حذف المسافات، والترتيب الأبجدي.',
                    'تسجيل ماكرو لخطوات المعالجة المتكررة وتطبيقها آلياً على الملفات بضغطة واحدة.',
                ],
            ],

            'stocktalk-ai' => [
                'slug' => 'stocktalk-ai',
                'title_en' => 'StockTalk AI WhatsApp Customer Support Bot',
                'title_ar' => 'روبوت الذكاء الاصطناعي وخدمة العملاء StockTalk AI',
                'category' => 'AI & Bots',
                'category_ar' => 'الذكاء الاصطناعي والروبوتات',
                'desc_en' => 'Intelligent conversational AI agent connected to company ERP databases via WhatsApp, answering stock inquiries, quoting prices, and placing orders 24/7.',
                'desc_ar' => 'مساعد ذكاء اصطناعي تفاعلي مربوط بأنظمة المخازن عبر واتساب للرد على العملاء، فحص توافر المنتجات، وتسجيل الطلبات لحظياً.',
                'img' => '/images/portfolio/stocktalk.png',
                'techs' => ['Python', 'OpenAI API', 'Laravel Webhooks', 'Meta Cloud API', 'Redis'],
                'live_url' => null,
                'metrics' => [
                    'Response Time' => '< 1.8s AI Natural Reply',
                    'Integration' => 'Direct Live Database Queries',
                    'Availability' => '24/7/365 Automated Uptime',
                    'Accuracy' => 'Grounded ERP RAG Architecture',
                ],
                'highlights_en' => [
                    'RAG (Retrieval-Augmented Generation) connecting AI directly to live ERP inventory stock.',
                    'Understands natural Arabic and English conversational queries regarding product availability.',
                    'Automated checkout flow generating invoice links directly inside the chat window.',
                    'Seamless live human agent handoff when complex customer inquiries arise.',
                ],
                'highlights_ar' => [
                    'تقنية RAG لربط نموذج الذكاء الاصطناعي بقاعدة بيانات المخزون الحية بدقة تامة.',
                    'فهم اللهجات العربية المختلفة والإنجليزية والإجابة على استفسارات الأسعار والتوافر.',
                    'إتمام عمليات الشراء وتوليد روابط الفواتير والدفع الإلكتروني داخل المحادثة مباشرة.',
                    'تحويل ذكي للعميل إلى موظف بشري عند وجود استفسارات معقدة أو طلبات خاصة.',
                ],
            ],

            'fb-id-extractor' => [
                'slug' => 'fb-id-extractor',
                'title_en' => 'Facebook Audience & UID Extractor Extension',
                'title_ar' => 'إضافة استخراج المعرفات والجمهور المستهدف FB ID Extractor',
                'category' => 'Tools & Extensions',
                'category_ar' => 'الأدوات وإضافات المتصفح',
                'desc_en' => 'Chrome extension designed for digital marketers to analyze public group members, extract profile UIDs, and build high-relevance custom audience segments.',
                'desc_ar' => 'إضافة متصفح كروم مخصصة للمسوقين لاستخراج معرفات المستخدمين (UIDs) من المجموعات والتفاعلات لبناء جماهير إعلانية مخصصة.',
                'img' => '/images/portfolio/chrome-ext-fb-id.png',
                'techs' => ['JavaScript', 'Chrome Manifest V3', 'GraphQL Hook', 'DOM Observer'],
                'live_url' => null,
                'metrics' => [
                    'Extraction' => '5,000+ UIDs / Minute',
                    'Method' => 'Network GraphQL Interception',
                    'Export' => 'CSV, TXT, Excel Compatible',
                    'Safety' => 'Client-Side Local Storage',
                ],
                'highlights_en' => [
                    'Intercepts platform GraphQL response streams without triggering DOM rate limits.',
                    'Filters extracted members by country, employment title, and join date.',
                    'One-click export directly into standard CSV format ready for Ads Manager upload.',
                    'Runs completely in the background without disturbing active browsing sessions.',
                ],
                'highlights_ar' => [
                    'اعتراض مباشر لحزم بيانات GraphQL للوصول لأقصى سرعة دون قيود الـ DOM.',
                    'فلترة وتصفية الأعضاء المستخرجين حسب الموقع الجغرافي والمسمى الوظيفي.',
                    'تصدير فوري بضغطة زر لملفات CSV متوافقة مع منصات الإعلانات الممولة.',
                    'عمل سلس في الخلفية دون التأثير على تصفح المستخدم العادي.',
                ],
            ],

            'khamsat-notifier' => [
                'slug' => 'khamsat-notifier',
                'title_en' => 'Khamsat Freelance Request Real-Time Notifier',
                'title_ar' => 'إضافة التنبيهات الفورية لمشاريع خمسات Khamsat Notifier',
                'category' => 'Tools & Extensions',
                'category_ar' => 'الأدوات وإضافات المتصفح',
                'desc_en' => 'Browser productivity extension continuously monitoring marketplace buyer requests and firing desktop sound and push alerts the instant a relevant project appears.',
                'desc_ar' => 'إضافة متصفح ذكية تراقب طلبات الخدمات غير الموجودة على موقع خمسات وترسل تنبيهات صوتية فورية لتقديم العروض أولاً.',
                'img' => '/images/portfolio/khamsat-notifier.jpg',
                'techs' => ['JavaScript', 'Web Notifications API', 'Chrome Extension', 'Audio API'],
                'live_url' => null,
                'metrics' => [
                    'Interval' => 'Instant Real-Time Stream',
                    'Filtering' => 'Keyword Whitelist & Blacklist',
                    'Alerts' => 'Native Desktop Sound & Toast',
                    'Efficiency' => '< 10MB Memory Footprint',
                ],
                'highlights_en' => [
                    'Instant alert popup with direct one-click link to submit proposals before competitors.',
                    'Custom keyword filter matching only projects in your specific technical specialties.',
                    'Sound alert selector with customizable notification chimes for urgent projects.',
                    'Zero resource hogging with optimized asynchronous fetch routines.',
                ],
                'highlights_ar' => [
                    'تنبيه فوري منبثق مع رابط مباشر لتقديم العرض على المشتري قبل باقي المنافسين.',
                    'فلتر كلمات مفتاحية دقيق يعرض فقط المشاريع المتوافقة مع تخصصك البرمجي.',
                    'أصوات تنبيه مخصصة تميز نوعية المشاريع العاجلة.',
                    'أداء خفيف جداً يستهلك أدنى قدر ممكن من موارد الجهاز والذاكرة.',
                ],
            ],

            'am-sms-gateway' => [
                'slug' => 'am-sms-gateway',
                'title_en' => 'Hardware-Bridged Android Automated SMS Gateway',
                'title_ar' => 'بوابة إرسال الرسائل القصيرة عبر هواتف الأندرويد SMS Gateway',
                'category' => 'Desktop & Automation',
                'category_ar' => 'برامج سطح المكتب والأتمتة',
                'desc_en' => 'Dual-layer telecommunication bridge allowing servers to dispatch automated OTP and transactional SMS directly through local Android SIM cards with webhook feedback.',
                'desc_ar' => 'نظام يربط السيرفرات السحابية بهواتف الأندرويد المحلية لإرسال رسائل التحقق (OTP) وتنبيهات المعاملات عبر شرائح SIM العادية.',
                'img' => '/images/portfolio/am-sms.jpg',
                'techs' => ['Android Java', 'Laravel API', 'WebSockets', 'SQLite', 'Background Service'],
                'live_url' => null,
                'metrics' => [
                    'Delivery' => '< 2s SMS Dispatch',
                    'Cost' => 'Zero Gateway Markups',
                    'Feedback' => 'Real-Time Delivery Webhooks',
                    'Reliability' => 'Offline Queue Auto-Resend',
                ],
                'highlights_en' => [
                    'Transforms any standard Android phone into an enterprise SMS gateway.',
                    'Direct REST API endpoints allowing any website or ERP to send SMS instantly.',
                    'Real-time delivery status reports confirming recipient phone receipt.',
                    'Automatic multi-SIM card load balancing distributing daily SMS package quotas.',
                ],
                'highlights_ar' => [
                    'تحويل أي هاتف أندرويد عادي إلى بوابة إرسال رسائل قصيرة SMS مؤسسية.',
                    'واجهة برمجية REST API تتيح لأي موقع أو نظام ERP إرسال الرسائل فوراً.',
                    'تقارير تسليم لحظية تؤكد وصول الرسالة لهاتف العميل بنجاح.',
                    'توزيع ذكي للرسائل بين شرائح الـ SIM المتعددة لاستغلال باقات الرسائل المجانية.',
                ],
            ],

            'qcoin-wallet' => [
                'slug' => 'qcoin-wallet',
                'title_en' => 'QCoin Digital Asset Wallet & Blockchain Explorer',
                'title_ar' => 'محفظة الأصول الرقمية والمدفوعات المشفرة QCoin',
                'category' => 'E-Commerce & Mobile',
                'category_ar' => 'متاجر وتطبيقات الموبايل',
                'desc_en' => 'Non-custodial crypto wallet and transaction tracker featuring real-time token valuation charts, QR address generator, and automated peer-to-peer escrow transfers.',
                'desc_ar' => 'محفظة وتطبيق لمتابعة وتداول الأصول الرقمية، يدعم رموز الاستجابة السريعة (QR)، أسعار الصرف الحية، وحماية المعاملات.',
                'img' => '/images/portfolio/qcoin-app.png',
                'techs' => ['Flutter', 'Node.js', 'Web3 APIs', 'PostgreSQL', 'TailwindCSS'],
                'live_url' => null,
                'metrics' => [
                    'Security' => 'Client-Side Key Encryption',
                    'Tracking' => 'Live Price Tickers',
                    'Transfers' => 'Instant QR Scanning',
                    'Auditing' => 'Full Ledger Explorer',
                ],
                'highlights_en' => [
                    'Encrypted key vault with biometric unlocking for secure on-device asset management.',
                    'Real-time market price charts with percentage changes and profit/loss calculation.',
                    'QR code scanning and generation for instant, error-free wallet address transfers.',
                    'Integrated transaction history explorer with transaction hash verification.',
                ],
                'highlights_ar' => [
                    'خزنة مشفرة بمصادقة البصمة لإدارة الأصول الرقمية بأعلى معايير الأمان.',
                    'رسوم بيانية لأسعار السوق المحدثة لحظياً مع حساب الأرباح والخسائر التلقائي.',
                    'توليد ومسح رموز الـ QR لتحويل الأموال واستقبالها بدون أي أخطاء في العناوين.',
                    'سجل معاملات تاريخي شامل مع فحص كود المعاملة (Tx Hash).',
                ],
            ],
        ];
    }

    /**
     * Get a specific project by slug.
     */
    public static function find(string $slug): ?array
    {
        $all = self::all();
        return $all[$slug] ?? null;
    }

    /**
     * Get all categories.
     */
    public static function categories(): array
    {
        return [
            'All' => ['en' => 'All Systems', 'ar' => 'جميع الأنظمة'],
            'ERP & Financials' => ['en' => 'ERP & Financials', 'ar' => 'أنظمة الحسابات و ERP'],
            'SaaS & Cloud' => ['en' => 'SaaS & Cloud', 'ar' => 'منصات سحابية SaaS'],
            'Desktop & Automation' => ['en' => 'Desktop & Automation', 'ar' => 'برامج سطح المكتب والأتمتة'],
            'E-Commerce & Mobile' => ['en' => 'E-Commerce & Mobile', 'ar' => 'متاجر وتطبيقات الموبايل'],
            'AI & Bots' => ['en' => 'AI & Bots', 'ar' => 'الذكاء الاصطناعي والروبوتات'],
            'Tools & Extensions' => ['en' => 'Tools & Extensions', 'ar' => 'الأدوات وإضافات المتصفح'],
        ];
    }
}
