<?php

namespace App\Services;

class ProjectEstimatorDataService extends BaseService
{
    /**
     * Get structured estimator configuration and items.
     *
     * @param float $exchangeRate
     * @return array
     */
    public function getEstimatorData(float $exchangeRate = 50.0): array
    {
        $platforms = [
            'web' => [
                'key' => 'web',
                'title' => 'Website / Web App',
                'title_ar' => 'موقع إلكتروني / تطبيق ويب',
                'rate_usd' => 10,
                'rate_egp' => round(10 * $exchangeRate),
                'unit' => 'Page',
                'unit_ar' => 'صفحة',
                'icon' => 'Globe',
                'badge' => '$10/page',
                'description' => 'Responsive web applications, corporate websites, customer portals, and SaaS platforms.',
            ],
            'mobile' => [
                'key' => 'mobile',
                'title' => 'Mobile App (iOS & Android)',
                'title_ar' => 'تطبيق هاتف (iOS و Android)',
                'rate_usd' => 15,
                'rate_egp' => round(15 * $exchangeRate),
                'unit' => 'Screen',
                'unit_ar' => 'شاشة',
                'icon' => 'Smartphone',
                'badge' => '$15/screen',
                'description' => 'Cross-platform native mobile applications for iOS and Android with high performance.',
            ],
            'desktop' => [
                'key' => 'desktop',
                'title' => 'Desktop Software',
                'title_ar' => 'برنامج كمبيوتر ومكتبي',
                'rate_usd' => 25,
                'rate_egp' => round(25 * $exchangeRate),
                'unit' => 'Screen',
                'unit_ar' => 'شاشة',
                'icon' => 'Monitor',
                'badge' => '$25/screen',
                'description' => 'Offline-first desktop software for Windows, POS point-of-sale systems, and cashier terminals.',
            ],
        ];

        $categories = [
            ['id' => 'all', 'title' => 'All Modules', 'title_ar' => 'جميع الإضافات'],
            ['id' => 'ai_automation', 'title' => 'AI & Automation', 'title_ar' => 'الذكاء الاصطناعي والأتمتة'],
            ['id' => 'ecommerce', 'title' => 'E-Commerce & Payments', 'title_ar' => 'التجارة الإلكترونية والمدفوعات'],
            ['id' => 'core', 'title' => 'Core & Management', 'title_ar' => 'الإدارة والتحكم الأساسي'],
            ['id' => 'infrastructure', 'title' => 'Cloud & Security', 'title_ar' => 'السحابة والأمان'],
            ['id' => 'marketing', 'title' => 'Marketing & SEO', 'title_ar' => 'التسويق وتهيئه محركات البحث'],
            ['id' => 'optimization', 'title' => 'Speed & Bug Fixing', 'title_ar' => 'السرعة وإصلاح الأخطاء'],
        ];

        $modules = [
            'web' => [
                [
                    'id' => 'web_admin_panel',
                    'title' => 'Web Admin Dashboard',
                    'category' => 'core',
                    'price_usd' => 100,
                    'price_egp' => round(100 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Shield',
                    'desc' => 'Full administrative portal to manage orders, analytics, content, and users.',
                ],
                [
                    'id' => 'web_ai_chatbot',
                    'title' => 'AI Smart Assistant (OpenAI / GPT)',
                    'category' => 'ai_automation',
                    'price_usd' => 45,
                    'price_egp' => round(45 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Bot',
                    'desc' => 'Intelligent AI chatbot trained on your business data to answer customer inquiries 24/7.',
                ],
                [
                    'id' => 'web_whatsapp_bot',
                    'title' => 'WhatsApp Automation & OTP Alerts',
                    'category' => 'ai_automation',
                    'price_usd' => 40,
                    'price_egp' => round(40 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'MessageSquare',
                    'desc' => 'Instant WhatsApp notifications on new orders, OTP phone verification, and click-to-chat bot.',
                ],
                [
                    'id' => 'web_whatsapp_channels',
                    'title' => 'WhatsApp Channels Integration',
                    'category' => 'ai_automation',
                    'price_usd' => 35,
                    'price_egp' => round(35 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Radio',
                    'desc' => 'Direct broadcast and interactive communication integration with WhatsApp Channels via official APIs.',
                ],
                [
                    'id' => 'web_telegram_bot',
                    'title' => 'Telegram Bot Management',
                    'category' => 'ai_automation',
                    'price_usd' => 30,
                    'price_egp' => round(30 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Send',
                    'desc' => 'Custom Telegram bot with command workflows, interactive menus, broadcast controls, and admin management.',
                ],
                [
                    'id' => 'web_telegram_channel_collector',
                    'title' => 'Telegram Channel Collection',
                    'category' => 'ai_automation',
                    'price_usd' => 25,
                    'price_egp' => round(25 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Database',
                    'desc' => 'Automated data harvesting and continuous tracking of posts, media, and updates from Telegram channels.',
                ],
                [
                    'id' => 'web_whatsapp_channel_collector',
                    'title' => 'WhatsApp Channel Collection',
                    'category' => 'ai_automation',
                    'price_usd' => 30,
                    'price_egp' => round(30 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'MessageSquare',
                    'desc' => 'Real-time and batch extraction of messages, updates, and channel broadcasts from WhatsApp.',
                ],
                [
                    'id' => 'web_auto_data_jobs',
                    'title' => 'Automated Data Collection Jobs',
                    'category' => 'ai_automation',
                    'price_usd' => 35,
                    'price_egp' => round(35 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Clock',
                    'desc' => 'Automated background cron jobs and scheduled tasks for recurring data fetching and syncing.',
                ],
                [
                    'id' => 'web_content_deduplication',
                    'title' => 'Content Deduplication & Processing',
                    'category' => 'ai_automation',
                    'price_usd' => 25,
                    'price_egp' => round(25 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Filter',
                    'desc' => 'Advanced similarity matching, duplicate removal, text filtering, and automated content cleanup pipeline.',
                ],
                [
                    'id' => 'web_metaapi_mt5',
                    'title' => 'MetaApi MT5 Broker Connection & Trading Execution',
                    'title_ar' => 'ربط MetaApi وبروكر MT5 وتنفيذ الصفقات المباشرة',
                    'category' => 'ai_automation',
                    'price_usd' => 60,
                    'price_egp' => round(60 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Cpu',
                    'desc' => 'Direct MetaApi cloud integration with MetaTrader 5 (MT5) for live account connection, automated trade execution, and balance sync.',
                ],
                [
                    'id' => 'web_tradingview_chart',
                    'title' => 'TradingView Charting Library + Broker API Integration',
                    'title_ar' => 'شارتات TradingView التفاعلية والربط البرمجي للوسيط',
                    'category' => 'ai_automation',
                    'price_usd' => 50,
                    'price_egp' => round(50 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'LineChart',
                    'desc' => 'Interactive TradingView advanced charting library integration with broker REST/WebSocket data feeds and custom indicators.',
                ],
                [
                    'id' => 'web_autotrade_engine',
                    'title' => 'Auto-Trade Engine & Lifecycle Logic',
                    'title_ar' => 'محرك التداول الآلي وإدارة دورة حياة الأوامر',
                    'category' => 'ai_automation',
                    'price_usd' => 60,
                    'price_egp' => round(60 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Zap',
                    'desc' => 'Algorithmic auto-trade execution engine with order queueing, slippage protection, and complete trade lifecycle state management.',
                ],
                [
                    'id' => 'web_loss_limits_closure',
                    'title' => 'Global Loss Limits & Automatic Position Closure',
                    'title_ar' => 'حدود الخسارة العامة والإغلاق التلقائي للصفقات',
                    'category' => 'ai_automation',
                    'price_usd' => 40,
                    'price_egp' => round(40 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'ShieldCheck',
                    'desc' => 'Automated risk management engine with global equity drawdown safeguards, daily loss ceilings, and instant emergency position liquidation.',
                ],
                [
                    'id' => 'web_signal_analytics',
                    'title' => 'Signal Analytics & Trading Performance Calculations',
                    'title_ar' => 'تحليلات الإشارات وحسابات أداء التداول والأرباح',
                    'category' => 'ai_automation',
                    'price_usd' => 35,
                    'price_egp' => round(35 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'LineChart',
                    'desc' => 'Quantitative performance metrics, real-time PnL tracking, win rate analytics, drawdown charts, and trading risk exposure reports.',
                ],
                [
                    'id' => 'web_channel_mirror',
                    'title' => 'Channel Mirror / Signal Routing',
                    'title_ar' => 'مرآة القنوات وإعادة توجيه إشارات التداول',
                    'category' => 'ai_automation',
                    'price_usd' => 45,
                    'price_egp' => round(45 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Radio',
                    'desc' => 'Automated signal mirroring pipeline with channel-to-channel routing, custom lot-size scaling, and multi-account trade copying.',
                ],
                [
                    'id' => 'web_gateways',
                    'title' => 'Online Payment Gateways',
                    'category' => 'ecommerce',
                    'price_usd' => 20,
                    'price_egp' => round(20 * $exchangeRate),
                    'platform' => 'web',
                    'isCounter' => true,
                    'max' => 5,
                    'icon' => 'CreditCard',
                    'desc' => 'Direct checkout integration (Paymob, Fawry, Stripe, PayPal, Tabby, Tamara, Visa/Mastercard).',
                ],
                [
                    'id' => 'web_pdf_invoicing',
                    'title' => 'Automated PDF Invoices & Receipts',
                    'category' => 'ecommerce',
                    'price_usd' => 25,
                    'price_egp' => round(25 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Receipt',
                    'desc' => 'Auto-generate branded PDF invoices and tax receipts sent directly to customer emails.',
                ],
                [
                    'id' => 'web_multi_currency',
                    'title' => 'Multi-Currency & GeoIP Country Detection',
                    'category' => 'ecommerce',
                    'price_usd' => 25,
                    'price_egp' => round(25 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Globe',
                    'desc' => 'Automatic visitor country detection with live exchange rates conversion (EGP, SAR, AED, USD).',
                ],
                [
                    'id' => 'web_marketing_pixels',
                    'title' => 'Marketing Pixels & GA4 Analytics',
                    'category' => 'marketing',
                    'price_usd' => 20,
                    'price_egp' => round(20 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'LineChart',
                    'desc' => 'Server-side CAPI and client tracking setup for Meta Pixel, TikTok Pixel, Snap & Google Analytics 4.',
                ],
                [
                    'id' => 'web_seo_speed',
                    'title' => 'Technical SEO & Search Indexing',
                    'category' => 'marketing',
                    'price_usd' => 25,
                    'price_egp' => round(25 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Search',
                    'desc' => 'Google sitemap indexing, OpenGraph rich social snippets, schema markup, and metadata tags.',
                ],
                [
                    'id' => 'web_auth_roles',
                    'title' => 'Multi-tier Roles & Permissions',
                    'category' => 'core',
                    'price_usd' => 40,
                    'price_egp' => round(40 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Lock',
                    'desc' => 'Secure signup/login with granular permissions (Super Admin, Manager, Accountant, Client).',
                ],
                [
                    'id' => 'web_multilingual',
                    'title' => 'Multilingual Interface (AR / EN)',
                    'category' => 'core',
                    'price_usd' => 30,
                    'price_egp' => round(30 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Languages',
                    'desc' => 'Seamless dual language interface with dynamic RTL and LTR direction switching.',
                ],
                [
                    'id' => 'web_security_firewall',
                    'title' => 'Security Firewall & DDoS Shield',
                    'category' => 'infrastructure',
                    'price_usd' => 40,
                    'price_egp' => round(40 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'ShieldCheck',
                    'desc' => 'WAF firewall, SQL injection / XSS protection, automated rate limiting, and brute-force lockouts.',
                ],
                [
                    'id' => 'web_cloud_db',
                    'title' => 'Cloud Database & SSL Deployment',
                    'category' => 'infrastructure',
                    'price_usd' => 35,
                    'price_egp' => round(35 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Database',
                    'desc' => 'Production server provisioning, SSL certificates, automated database backups, and DNS go-live.',
                ],
                [
                    'id' => 'web_external_api',
                    'title' => 'External REST APIs & Webhooks',
                    'category' => 'infrastructure',
                    'price_usd' => 60,
                    'price_egp' => round(60 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Cpu',
                    'desc' => 'Integration with shipping companies (Aramex, Bosta, DHL), external ERPs, or custom CRMs.',
                ],
                [
                    'id' => 'web_bug_fix',
                    'title' => 'Web Bug Fixing & Troubleshooting',
                    'category' => 'optimization',
                    'price_usd' => 35,
                    'price_egp' => round(35 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Bug',
                    'desc' => 'Diagnosis and fixing of frontend UI bugs, broken responsive mobile layouts, and backend errors.',
                ],
                [
                    'id' => 'web_performance_tune',
                    'title' => 'Speed Tuning & 90+ PageSpeed',
                    'category' => 'optimization',
                    'price_usd' => 30,
                    'price_egp' => round(30 * $exchangeRate),
                    'platform' => 'web',
                    'icon' => 'Zap',
                    'desc' => 'Query optimization, asset minification, Redis caching, and achieving 90+ Google PageSpeed score.',
                ],
            ],
            'mobile' => [
                [
                    'id' => 'mobile_admin_panel',
                    'title' => 'Mobile Web Admin & REST API',
                    'category' => 'core',
                    'price_usd' => 120,
                    'price_egp' => round(120 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'Shield',
                    'desc' => 'Dedicated cloud control panel & REST API backend to manage app content, notifications & users.',
                ],
                [
                    'id' => 'mobile_ai_assistant',
                    'title' => 'In-App AI Conversational Bot',
                    'category' => 'ai_automation',
                    'price_usd' => 50,
                    'price_egp' => round(50 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'Bot',
                    'desc' => 'Interactive AI assistant embedded within the mobile app for smart user recommendations and support.',
                ],
                [
                    'id' => 'mobile_push_notifications',
                    'title' => 'Push Notifications (FCM / OneSignal)',
                    'category' => 'ai_automation',
                    'price_usd' => 35,
                    'price_egp' => round(35 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'BellRing',
                    'desc' => 'Instant push notifications to engage users, announce special offers, and broadcast alerts.',
                ],
                [
                    'id' => 'mobile_biometric_auth',
                    'title' => 'Biometric Login (FaceID & Fingerprint)',
                    'category' => 'core',
                    'price_usd' => 30,
                    'price_egp' => round(30 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'Fingerprint',
                    'desc' => 'Fast 1-touch secure authentication via Apple FaceID and Android Fingerprint sensors.',
                ],
                [
                    'id' => 'mobile_upload_google_play',
                    'title' => 'Upload APK/AAB to Google Play Store',
                    'title_ar' => 'رفع التطبيق على متجر جوجل بلاي (Google Play)',
                    'category' => 'infrastructure',
                    'price_usd' => 30,
                    'price_egp' => round(30 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'UploadCloud',
                    'desc' => 'Google Play Console configuration, keystore signing, release track setup, and review submission.',
                ],
                [
                    'id' => 'mobile_upload_apple_store',
                    'title' => 'Upload IPA/iOS to Apple App Store',
                    'title_ar' => 'رفع التطبيق على متجر آب ستور (Apple App Store)',
                    'category' => 'infrastructure',
                    'price_usd' => 30,
                    'price_egp' => round(30 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'UploadCloud',
                    'desc' => 'Apple Developer certificate, provisioning profile, TestFlight build, and App Store review submission.',
                ],
                [
                    'id' => 'mobile_app_stores',
                    'title' => 'App Store & Google Play Publishing (Bundle)',
                    'category' => 'infrastructure',
                    'price_usd' => 50,
                    'price_egp' => round(50 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'UploadCloud',
                    'desc' => 'Release bundle building, metadata formatting, store assets generation, and submission for approvals.',
                ],
                [
                    'id' => 'mobile_gateways',
                    'title' => 'In-App Payment Gateways',
                    'category' => 'ecommerce',
                    'price_usd' => 20,
                    'price_egp' => round(20 * $exchangeRate),
                    'platform' => 'mobile',
                    'isCounter' => true,
                    'max' => 5,
                    'icon' => 'CreditCard',
                    'desc' => 'Mobile in-app payments (Apple Pay, Google Pay, Paymob SDK, Stripe Mobile).',
                ],
                [
                    'id' => 'mobile_social_auth',
                    'title' => 'Social & Apple/Google Login',
                    'category' => 'core',
                    'price_usd' => 35,
                    'price_egp' => round(35 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'Lock',
                    'desc' => '1-tap sign-in with Google, Apple ID, Phone OTP, and email auth.',
                ],
                [
                    'id' => 'mobile_gps_maps',
                    'title' => 'GPS Maps & Geolocation Tracking',
                    'category' => 'core',
                    'price_usd' => 45,
                    'price_egp' => round(45 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'MapPin',
                    'desc' => 'Interactive Google Maps address picker, turn-by-turn routing, and live courier tracking.',
                ],
                [
                    'id' => 'mobile_live_chat',
                    'title' => 'In-App Live Support Chat',
                    'category' => 'ai_automation',
                    'price_usd' => 35,
                    'price_egp' => round(35 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'MessageSquare',
                    'desc' => 'Real-time WebSocket chat between users and customer service support agents.',
                ],
                [
                    'id' => 'mobile_deep_linking',
                    'title' => 'Deep Linking & Dynamic Share Links',
                    'category' => 'marketing',
                    'price_usd' => 25,
                    'price_egp' => round(25 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'Share2',
                    'desc' => 'Direct smart URLs that open specific screens, products, or offers directly inside the installed app.',
                ],
                [
                    'id' => 'mobile_multilingual',
                    'title' => 'Multilingual App UI (AR / EN)',
                    'category' => 'core',
                    'price_usd' => 30,
                    'price_egp' => round(30 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'Languages',
                    'desc' => 'Bilingual mobile localization with RTL / LTR dynamic interface layout adjustment.',
                ],
                [
                    'id' => 'mobile_external_api',
                    'title' => 'Mobile External REST APIs',
                    'category' => 'infrastructure',
                    'price_usd' => 60,
                    'price_egp' => round(60 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'Cpu',
                    'desc' => 'Syncing mobile app data with third-party inventory, delivery, or CRM systems.',
                ],
                [
                    'id' => 'mobile_bug_fix',
                    'title' => 'Mobile Bug Fixing & Crash Resolution',
                    'category' => 'optimization',
                    'price_usd' => 40,
                    'price_egp' => round(40 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'Bug',
                    'desc' => 'Fixing ANR/crashes, memory leaks, and Android/iOS OS version compatibility issues.',
                ],
                [
                    'id' => 'mobile_performance_tune',
                    'title' => 'App Speed & 60FPS Optimization',
                    'category' => 'optimization',
                    'price_usd' => 35,
                    'price_egp' => round(35 * $exchangeRate),
                    'platform' => 'mobile',
                    'icon' => 'Zap',
                    'desc' => 'Smooth scroll performance, reduced battery drain, and minimized app package size.',
                ],
            ],
            'desktop' => [
                [
                    'id' => 'desktop_web_sync',
                    'title' => 'Cloud Master Sync & Web Portal',
                    'category' => 'infrastructure',
                    'price_usd' => 130,
                    'price_egp' => round(130 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'UploadCloud',
                    'desc' => 'Centralized cloud server synchronization across all branches with online managerial reports.',
                ],
                [
                    'id' => 'desktop_e_invoicing_tax',
                    'title' => 'Electronic Invoicing (ZATCA / ETA Tax)',
                    'category' => 'ecommerce',
                    'price_usd' => 60,
                    'price_egp' => round(60 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'Receipt',
                    'desc' => 'Integration with tax authorities (Egyptian Tax Authority ETA / Saudi ZATCA Phase 2 QR-code compliance).',
                ],
                [
                    'id' => 'desktop_whatsapp_receipts',
                    'title' => 'WhatsApp Invoice Direct Dispatch',
                    'category' => 'ai_automation',
                    'price_usd' => 40,
                    'price_egp' => round(40 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'MessageSquare',
                    'desc' => 'Automatically send PDF tax invoices and receipts directly to customer WhatsApp right upon checkout.',
                ],
                [
                    'id' => 'desktop_pos_printing',
                    'title' => 'Thermal POS & Barcode Label Printing',
                    'category' => 'ecommerce',
                    'price_usd' => 40,
                    'price_egp' => round(40 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'Barcode',
                    'desc' => 'Thermal receipt printing (80mm/58mm), custom invoice designer, and barcode product sticker printing.',
                ],
                [
                    'id' => 'desktop_offline_db',
                    'title' => '100% Offline Database Engine',
                    'category' => 'infrastructure',
                    'price_usd' => 45,
                    'price_egp' => round(45 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'HardDrive',
                    'desc' => 'Local SQLite/SQL Server storage that works 100% uninterrupted without internet access.',
                ],
                [
                    'id' => 'desktop_auto_cloud_backup',
                    'title' => 'Encrypted Cloud Auto-Backup',
                    'category' => 'infrastructure',
                    'price_usd' => 30,
                    'price_egp' => round(30 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'CloudRain',
                    'desc' => 'Automated daily backup of system database to Google Drive / AWS S3 with AES-256 encryption.',
                ],
                [
                    'id' => 'desktop_serial_license',
                    'title' => 'Hardware Serial Key & Licensing',
                    'category' => 'infrastructure',
                    'price_usd' => 50,
                    'price_egp' => round(50 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'KeyRound',
                    'desc' => 'Machine hardware lock protection with encrypted serial license key activation and trial period.',
                ],
                [
                    'id' => 'desktop_user_roles',
                    'title' => 'Cashier Shifts & Anti-Fraud Audit Log',
                    'category' => 'core',
                    'price_usd' => 40,
                    'price_egp' => round(40 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'Lock',
                    'desc' => 'Shift closing receipts, supervisor override permissions, and strict audit logs preventing cashier fraud.',
                ],
                [
                    'id' => 'desktop_reporting_export',
                    'title' => 'Excel / PDF Export & Financial BI',
                    'category' => 'core',
                    'price_usd' => 30,
                    'price_egp' => round(30 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'FileSpreadsheet',
                    'desc' => 'Financial profit/loss charts, sales trends, inventory valuation, and 1-click Excel/PDF export.',
                ],
                [
                    'id' => 'desktop_device_scanner',
                    'title' => 'Weight Scale & Scanner Hardware Sync',
                    'category' => 'infrastructure',
                    'price_usd' => 50,
                    'price_egp' => round(50 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'Cpu',
                    'desc' => 'Direct COM port / USB communication with electronic weight scales, cash drawers, and scanners.',
                ],
                [
                    'id' => 'desktop_bug_fix',
                    'title' => 'Desktop Bug Fixing & Data Repair',
                    'category' => 'optimization',
                    'price_usd' => 45,
                    'price_egp' => round(45 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'Bug',
                    'desc' => 'Fixing unhandled exceptions/crashes, database index corruption, and printer communication errors.',
                ],
                [
                    'id' => 'desktop_performance_tune',
                    'title' => 'Fast Query & Index Tuning',
                    'category' => 'optimization',
                    'price_usd' => 40,
                    'price_egp' => round(40 * $exchangeRate),
                    'platform' => 'desktop',
                    'icon' => 'Zap',
                    'desc' => 'Instant search indexing and fast loading under heavy transaction loads (100k+ records).',
                ],
            ],
        ];

        $discountPolicy = [
            'bundle_discount_percentage' => 20,
            'bundle_condition' => 'Applies automatically when Web + Mobile + Desktop platforms are all selected.',
            'guarantee' => '100% transparent pricing, source code delivery, and 30-day post-delivery technical warranty.',
        ];

        return [
            'overview' => [
                'title' => 'Project Cost & Budget Estimator',
                'title_ar' => 'حاسبة تكلفة المشاريع والبرمجيات',
                'tagline' => 'Instant, transparent estimation for Websites, Mobile Apps, and Desktop software.',
                'tagline_ar' => 'تقدير فوري وشفاف لتكلفة المواقع وتطبيقات الموبايل وبرامج سطح المكتب.',
                'direct_whatsapp' => '+20 101 521 8548',
            ],
            'platforms' => $platforms,
            'categories' => $categories,
            'modules' => $modules,
            'discount_policy' => $discountPolicy,
            'exchangeRate' => (float)$exchangeRate,
            'supported_currencies' => ['USD', 'EGP'],
            'quotation_api' => [
                'endpoint' => route('public.quotation.generate'),
                'method' => 'POST',
            ],
        ];
    }
}
