<?php
$dir = new RecursiveIteratorIterator(new RecursiveDirectoryIterator("Modules/Booking/tests"));
foreach ($dir as $file) {
    if ($file->isFile() && $file->getExtension() === "php") {
        $content = file_get_contents($file->getPathname());
        $original = $content;

        // Specifically target User::factory()->create(...) matches
        $content = preg_replace_callback('/User::factory\(\)->create\(\[(.*?)\]\)/s', function($m) {
            $inner = $m[1];
            // Remove 'tenant_id' => ... from $inner
            $inner = preg_replace("/'tenant_id'\s*=>\s*[^,\]]+,?\s*/", "", $inner);
            // clean up trailing commas
            $inner = rtrim(trim($inner), ',');
            return "User::factory()->create([" . $inner . "])";
        }, $content);
        
        // Also target forceCreate in booking to add booking_event_type_id and starts_at
        $content = preg_replace_callback('/Booking::forceCreate\(\[(.*?)\]\)/s', function($m) {
            $inner = $m[1];
            if (strpos($inner, "'booking_event_type_id'") === false) {
                if ($inner !== '') $inner .= ", ";
                $inner .= "'booking_event_type_id' => 1";
            }
            if (strpos($inner, "'starts_at'") === false) {
                if ($inner !== '') $inner .= ", ";
                $inner .= "'starts_at' => now()";
            }
            return "Booking::forceCreate([" . $inner . "])";
        }, $content);

        // fix empty arrays generated by previous replacement
        $content = str_replace("User::factory()->create([])", "User::factory()->create()", $content);

        if ($content !== $original) {
            file_put_contents($file->getPathname(), $content);
            echo "Updated: " . $file->getPathname() . "\n";
        }
    }
}
