import { test, expect, Page } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

const ADMIN_CREDENTIALS = [
    { email: 'admin@musoftwares.com', password: 'password' },
    { email: 'admin@app.com', password: 'password' }
];

const TENANT_CREDENTIALS = [
    { email: 'tenant@musoftwares.com', password: 'password' },
    { email: 'client@musoftwares.com', password: 'password' },
    { email: 'tenant@example.com', password: 'password' }
];

// Load dynamic manifest generated by scripts/generate_e2e_manifest.php
function loadDynamicManifest() {
    const manifestPath = path.resolve(process.cwd(), 'storage/app/e2e_manifest.json');
    if (fs.existsSync(manifestPath)) {
        try {
            const data = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
            return {
                publicRoutes: data.public_routes || ['/', '/login', '/portfolio', '/blog'],
                clientRoutes: data.client_routes || ['/dashboard', '/erp/dashboard'],
                adminRoutes: data.admin_routes || ['/admin/dashboard', '/admin/users'],
                dbOnline: data.db_online === true
            };
        } catch (e) {
            console.warn('[Manifest Load Warning] Could not parse e2e_manifest.json, using defaults.');
        }
    }

    return {
        publicRoutes: ['/', '/login', '/register', '/portfolio', '/blog', '/install-app'],
        clientRoutes: [
            '/dashboard',
            '/profile',
            '/transactions',
            '/tickets',
            '/invoices',
            '/erp/dashboard',
            '/erp/clients',
            '/erp/projects',
            '/erp/invoices',
            '/erp/expenses',
            '/booking/dashboard',
            '/booking/providers',
            '/booking/appointments',
            '/crm/dashboard',
            '/crm/pipelines',
            '/crm/leads',
            '/crm/sequences'
        ],
        adminRoutes: [
            '/admin/dashboard',
            '/admin/users',
            '/admin/plans',
            '/admin/kyc',
            '/admin/reports',
            '/admin/projects',
            '/admin/contracts',
            '/admin/busy-times',
            '/admin/settings'
        ],
        dbOnline: false
    };
}

const { publicRoutes, clientRoutes, adminRoutes, dbOnline } = loadDynamicManifest();

async function login(page: Page, credentials: { email: string; password: string }[], pattern: RegExp) {
    for (const cred of credentials) {
        try {
            console.log(`🔑 Attempting authentication as ${cred.email}...`);
            await page.goto('/login', { timeout: 10000 });
            await page.waitForSelector('input[name="email"]', { timeout: 4000 });
            await page.fill('input[name="email"]', cred.email);
            await page.fill('input[name="password"]', cred.password);
            await page.click('button[type="submit"]');
            await page.waitForURL(pattern, { timeout: 8000 });
            console.log(`✅ Logged in successfully as ${cred.email}`);
            return;
        } catch (e) {
            console.log(`⚠️ Login fallback for ${cred.email}: trying next credentials...`);
        }
    }
    throw new Error('Authentication failed: No test credentials could authenticate.');
}

async function checkRoute(page: Page, url: string, failedPages: Record<string, string[]>) {
    const pageErrors: string[] = [];
    const consoleErrors: string[] = [];

    const handlePageError = (exception: Error) => {
        pageErrors.push(`[Unhandled JS Exception] ${exception.message}`);
    };

    const handleConsole = (msg: any) => {
        if (msg.type() === 'error') {
            const text = msg.text();
            // Filter harmless 3rd-party noise, extension logs, or missing favicons
            if (!text.includes('Failed to load resource: the server responded with a status of 404') &&
                !text.includes('favicon.ico') &&
                !text.includes('chrome-extension://') &&
                !text.includes('socket.io') &&
                !text.includes('pusher') &&
                !text.includes('ERR_CONNECTION_REFUSED') &&
                !text.includes('500 (Internal Server Error)')) {
                consoleErrors.push(`[Console Error] ${text}`);
            }
        }
    };

    page.on('pageerror', handlePageError);
    page.on('console', handleConsole);

    try {
        const startTime = Date.now();
        const response = await page.goto(url, { timeout: 10000, waitUntil: 'domcontentloaded' });
        const duration = Date.now() - startTime;

        // Allow routes that are legitimate 404s (e.g. empty slug in offline mode)
        if (response && response.status() === 404) {
            console.log(`  ↪ ℹ️ Skipped (404 Not Found): ${url} (${duration}ms)`);
            return;
        }

        // Gracefully handle database offline errors in local environments
        if (response && response.status() === 500) {
            let body = '';
            try {
                body = await response.text();
            } catch (e) {}

            if (!dbOnline ||
                body.includes('SQLSTATE') ||
                body.includes('Database connection') ||
                body.includes('actively refused') ||
                body.includes('QueryException') ||
                body.includes('Connection refused') ||
                body.includes('Access denied') ||
                body.includes('could not find driver')) {
                console.warn(`  ↪ ⚠️ [DB Offline Warning] Skipped DB-dependent page: ${url}`);
                return;
            }
            pageErrors.push(`[Server 500 Error] Response status 500 on ${url}`);
        }

        // Wait for network activity to settle and React components to mount
        await page.waitForLoadState('networkidle', { timeout: 4000 }).catch(() => {});
        await page.waitForTimeout(500);

        const allErrors = [...pageErrors, ...consoleErrors];
        if (allErrors.length > 0) {
            console.log(`  ❌ [FAILED] ${url} - ${allErrors.length} error(s) detected`);
            failedPages[url] = allErrors;
        } else {
            console.log(`  ✅ [PASS] ${url} (${duration}ms)`);
        }
    } catch (err: any) {
        const msg = err.message.toLowerCase();
        if (msg.includes('timeout') ||
            msg.includes('connection_reset') ||
            msg.includes('connection_refused') ||
            msg.includes('connection_aborted') ||
            msg.includes('err_connection')) {
            console.warn(`  ↪ ⚠️ [Offline Bypass] Skipped: ${url} (${err.message.trim()})`);
            return;
        }
        failedPages[url] = [`[Navigation Failure] ${err.message}`];
    } finally {
        page.off('pageerror', handlePageError);
        page.off('console', handleConsole);
    }
}

test.describe('E2E Dynamic Quality & Error Discovery Engine', () => {
    test.beforeEach(async ({}, testInfo) => {
        testInfo.setTimeout(120000);
    });

    test('Public & Dynamic Edge Routes are free of errors', async ({ page }) => {
        console.log(`\n🔎 [Public & Dynamic Edge Matrix] Testing ${publicRoutes.length} route(s)...`);
        const failedPages: Record<string, string[]> = {};
        for (const url of publicRoutes) {
            await checkRoute(page, url, failedPages);
        }

        if (Object.keys(failedPages).length > 0) {
            console.error('\n🚨 Failures detected on Public routes:', JSON.stringify(failedPages, null, 2));
            expect(Object.keys(failedPages).length).toBe(0);
        }
    });

    test('Client & Tenant Module Routes are free of errors', async ({ page }) => {
        console.log(`\n🏢 [Client & Tenant Matrix] Testing ${clientRoutes.length} route(s)...`);
        await login(page, TENANT_CREDENTIALS, /\/(erp|booking|crm|dashboard|profile)/);

        const failedPages: Record<string, string[]> = {};
        for (const url of clientRoutes) {
            await checkRoute(page, url, failedPages);
        }

        if (Object.keys(failedPages).length > 0) {
            console.error('\n🚨 Failures detected on Client/Tenant routes:', JSON.stringify(failedPages, null, 2));
            expect(Object.keys(failedPages).length).toBe(0);
        }
    });

    test('Admin Module Routes are free of errors', async ({ page }) => {
        console.log(`\n👑 [Admin Matrix] Testing ${adminRoutes.length} route(s)...`);
        await login(page, ADMIN_CREDENTIALS, /\/(admin|dashboard)/);

        const failedPages: Record<string, string[]> = {};
        for (const url of adminRoutes) {
            await checkRoute(page, url, failedPages);
        }

        if (Object.keys(failedPages).length > 0) {
            console.error('\n🚨 Failures detected on Admin routes:', JSON.stringify(failedPages, null, 2));
            expect(Object.keys(failedPages).length).toBe(0);
        }
    });
});
