<?php

namespace App\Http\Controllers\iSaaS;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Contract\StoreContractRequest;
use App\Http\Requests\Admin\Contract\UpdateContractRequest;
use App\Http\Requests\Admin\Contract\UpdateContractStatusRequest;
use App\Models\Contract;
use App\Models\Currency;
use App\Models\User;
use App\Services\ContractService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Inertia\Inertia;

class ContractController extends Controller
{
    public function __construct(
        protected ContractService $contractService
    ) {}

    public function create()
    {
        return Inertia::render('iSaaS/Contracts/Create', [
            'currencies' => Currency::all(),
        ]);
    }

    public function store(StoreContractRequest $request)
    {
        $data = $request->validated();
        $data['user_id'] = Auth::id(); // Ensure it belongs to the authenticated freelancer
        $contract = $this->contractService->createContract($data);

        return redirect()->route('isaas.contracts.edit', $contract->id)
            ->with('success', __('general.contract_created_successfully'));
    }

    public function edit(Contract $contract)
    {
        // Enforce data isolation
        if ($contract->user_id !== Auth::id()) {
            abort(403, __('general.unauthorized_action'));
        }

        $contract->load('user');

        return Inertia::render('iSaaS/Contracts/Edit', [
            'contract' => $contract,
            'currencies' => Currency::all(),
        ]);
    }

    public function update(UpdateContractRequest $request, Contract $contract)
    {
        // Enforce data isolation
        if ($contract->user_id !== Auth::id()) {
            abort(403, __('general.unauthorized_action'));
        }

        $this->contractService->updateContract($contract, $request->validated());

        return redirect()->route('isaas.contracts.index')
            ->with('success', __('general.contract_updated_successfully'));
    }

    public function index(Request $request)
    {
        $status = $request->query('status', 'all');
        $query = Contract::where('user_id', Auth::id());

        if ($status !== 'all') {
            $query->where('status', $status);
        }

        $contracts = $query->latest()->paginate(20)->through(function ($c) {
            return [
                'id' => $c->id,
                'user_id' => $c->user_id,
                'project_name' => $c->project_name,
                'project_description' => $c->project_description,
                'reference' => $c->reference,
                'prepared_by' => $c->prepared_by,
                'valid_until' => $c->valid_until ? $c->valid_until->toDateString() : null,
                'duration' => $c->duration,
                'total_amount' => $c->total_amount,
                'currency' => $c->currency,
                'currency_id' => $c->currency_id,
                'status' => $c->status,
                'client_name' => $c->client_name,
                'signed_at' => $c->signed_at,
                'created_at' => $c->created_at,
                'updated_at' => $c->updated_at,
            ];
        });

        return Inertia::render('iSaaS/Contracts/Index', [
            'contracts' => $contracts,
            'currentTab' => $status,
        ]);
    }

    public function updateStatus(UpdateContractStatusRequest $request, Contract $contract)
    {
        // Enforce data isolation
        if ($contract->user_id !== Auth::id()) {
            abort(403, __('general.unauthorized_action'));
        }

        $this->contractService->updateStatus($contract, $request->validated('status'));

        return redirect()->back()->with('success', __('general.contract_status_updated'));
    }

    public function destroy(Contract $contract)
    {
        // Enforce data isolation
        if ($contract->user_id !== Auth::id()) {
            abort(403, __('general.unauthorized_action'));
        }

        $this->contractService->deleteContract($contract);

        return redirect()->back()->with('success', __('general.contract_deleted_successfully'));
    }

    public function searchUsers(Request $request)
    {
        $search = $request->query('search');
        if (strlen($search) < 3) {
            return response()->json([]);
        }

        $users = User::where('name', 'like', "%{$search}%")
            ->orWhere('email', 'like', "%{$search}%")
            ->limit(10)
            ->get(['id', 'name', 'email']);

        return response()->json($users);
    }

    public function aiGenerate(Request $request)
    {
        return response()->json([
            'data' => [
                'project_description' => 'This is a sample project description generated by AI.',
                'description' => 'This contract outlines the terms of the project...',
                'payment_terms' => "20% upfront\n80% upon completion",
                'terms' => 'Standard terms apply.',
                'notes' => 'No special notes.',
                'duration' => '30 Days',
                'valid_until' => now()->addDays(30)->toDateString(),
                'includes_hosting' => false,
                'includes_support' => true,
                'support_duration' => '1 Month',
                'client_name' => 'Client Name',
                'key_features' => ['AI Feature 1', 'AI Feature 2'],
                'pricing_items' => [
                    ['item' => 'Development', 'description' => 'Full-stack development', 'hours' => 40, 'hourly_rate_egp' => 500],
                ],
            ],
        ]);
    }

    public function aiReview(Request $request)
    {
        return response()->json([
            'data' => [
                'refined_content' => $request->input('description')."\n\nReviewed and verified by AI.",
                'critical_issues' => [],
                'suggestions' => ['Looks good!'],
            ],
        ]);
    }
}
