type TranslationTree = Record<string, unknown>;

const DEFAULT_LOCALE = 'en';

/**
 * One lazy chunk per locale. The JSON files are generated by
 * `php artisan translations:export` (runs before every build).
 */
const localeLoaders = import.meta.glob<TranslationTree>('../lang/*.json', { import: 'default' });

let activeLocale: string | null = null;
let activeTranslations: TranslationTree = {};

function loaderFor(locale: string): (() => Promise<TranslationTree>) | undefined {
    return localeLoaders[`../lang/${locale}.json`] ?? localeLoaders[`../lang/${DEFAULT_LOCALE}.json`];
}

/**
 * Load the translations for one locale. Must finish before the app renders,
 * so `__()` can stay synchronous.
 */
export async function loadTranslations(locale?: string): Promise<void> {
    const targetLocale = locale || DEFAULT_LOCALE;
    if (activeLocale === targetLocale) return;

    const load = loaderFor(targetLocale);
    if (!load) {
        console.error(`[i18n] No translation file found for locale "${targetLocale}".`);
        return;
    }

    try {
        const translations = await load();
        activeTranslations = translations && typeof translations === 'object' ? translations : {};
        activeLocale = targetLocale;
    } catch (error) {
        // Render with raw keys / fallbacks rather than block the whole app.
        console.error(`[i18n] Failed to load translations for locale "${targetLocale}".`, error);
    }
}

export function getLoadedLocale(): string | null {
    return activeLocale;
}

function getNestedValue(obj: unknown, path: string): unknown {
    return path.split('.').reduce<unknown>(
        (acc, part) => (acc && typeof acc === 'object' ? (acc as TranslationTree)[part] : undefined),
        obj,
    );
}

/**
 * Synchronize html element attributes (lang & dir) with the application locale.
 */
export function syncDocumentDirection(locale?: string): void {
    if (typeof document === 'undefined') return;
    const currentLocale = locale || DEFAULT_LOCALE;
    document.documentElement.lang = currentLocale;
    document.documentElement.dir = currentLocale === 'ar' ? 'rtl' : 'ltr';
}

function applyReplacements(text: string, replacements: Record<string, string | number>): string {
    return Object.entries(replacements).reduce((result, [name, value]) => {
        // The lookahead stops ":name" from also matching inside ":names".
        const placeholder = new RegExp(`:${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?![A-Za-z0-9_])`, 'gi');
        return result.replace(placeholder, () => String(value));
    }, text);
}

/**
 * Frontend translation helper. Reads the locale loaded by `loadTranslations()`.
 */
export function __(key: string, replacements?: Record<string, string | number>, fallback?: string): string {
    if (!key || typeof key !== 'string') return '';

    const nested = getNestedValue(activeTranslations, key);
    const result = nested !== undefined ? nested : (activeTranslations[key] ?? (fallback || key));

    if (replacements && typeof replacements === 'object' && typeof result === 'string') {
        return applyReplacements(result, replacements);
    }

    return String(result);
}
