<?php

namespace App\Services\AI;

use App\Models\Currency;
use App\Models\CurrenciesExchange;
use App\Models\Invoice;
use App\Models\Project;
use App\Models\ProjectBoardItem;
use App\Models\ProjectComment;
use App\Models\Task;
use App\Models\Todo;
use App\Models\User;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class AiAgencyLaravelExecutor
{
    /**
     * Execution Phase: Updates project context and handles verified/confirmed actions.
     */
    public function execute(Project $project, array $decision, int $authorId): void
    {
        // 1. Update Project Context incrementally
        if (!empty($decision['context_updates']) && is_array($decision['context_updates'])) {
            $project->updateAiContext($decision['context_updates']);
        }

        // 2. Execute Admin Work Preparation if present (Developer Tasks, Admin Todos, Developer Notes)
        if (!empty($decision['admin_work']) && is_array($decision['admin_work'])) {
            $adminWork = $decision['admin_work'];

            // A. Create Developer Tasks under Admin Review
            if (!empty($adminWork['developer_tasks']) && is_array($adminWork['developer_tasks'])) {
                foreach ($adminWork['developer_tasks'] as $index => $taskTitle) {
                    $taskTitleClean = is_array($taskTitle) ? ($taskTitle['title'] ?? json_encode($taskTitle)) : (string) $taskTitle;
                    try {
                        ProjectBoardItem::firstOrCreate([
                            'project_id' => $project->id,
                            'title'      => trim($taskTitleClean),
                        ], [
                            'status'      => 'review', // Under Admin Review before dev starts
                            'sort_order'  => $index + 1,
                            'description' => 'Generated by AI Project Manager for Admin Review',
                        ]);
                    } catch (\Throwable $e) {
                        Log::warning('[AiAgencyLaravelExecutor] Could not create ProjectBoardItem task', ['error' => $e->getMessage()]);
                    }
                }
            }

            // B. Create Admin Todos
            if (!empty($adminWork['admin_todos']) && is_array($adminWork['admin_todos'])) {
                foreach ($adminWork['admin_todos'] as $todoTitle) {
                    $todoTitleClean = is_array($todoTitle) ? ($todoTitle['title'] ?? json_encode($todoTitle)) : (string) $todoTitle;
                    try {
                        Todo::firstOrCreate([
                            'project_id' => $project->id,
                            'title'      => trim($todoTitleClean),
                        ], [
                            'user_id'   => $project->user_id ?? $authorId,
                            'status'    => 'pending',
                        ]);
                    } catch (\Throwable $e) {
                        Log::warning('[AiAgencyLaravelExecutor] Could not create Todo', ['error' => $e->getMessage()]);
                    }
                }
            }

            // C. Save Developer Notes & Priorities to context
            $contextExtras = [];
            if (!empty($adminWork['developer_notes'])) {
                $contextExtras['developer_notes'] = $adminWork['developer_notes'];
            }
            if (!empty($adminWork['suggested_priorities'])) {
                $contextExtras['suggested_priorities'] = $adminWork['suggested_priorities'];
            }
            if (!empty($contextExtras)) {
                $project->updateAiContext($contextExtras);
            }
        }

        // 3. Post natural Arabic AI reply comment to chat thread
        $replyText = $decision['reply'] ?? 'تم استلام طلبك وتحديث بيانات المشروع بنجاح.';

        try {
            ProjectComment::create([
                'project_id'       => $project->id,
                'author_id'        => null,
                'guest_name'       => 'AI Project Manager',
                'body'             => $replyText,
                'commentable_type' => Project::class,
                'commentable_id'   => $project->id,
            ]);
        } catch (\Throwable $e) {
            Log::warning('[AiAgencyLaravelExecutor] Could not create ProjectComment', ['error' => $e->getMessage()]);
        }
    }

    /**
     * Execute Approved Invoice Creation (Triggered only upon explicit client confirmation).
     */
    public function executeApprovedInvoice(Project $project, float $amountUsd, string $description, int $authorId): Invoice
    {
        $user     = User::find($project->user_id) ?? User::find($authorId);
        $userCurr = $user?->currency_id ?? 1;

        $usdCurr = Currency::where('currency', 'USD')->first();
        $amountInUserCurrency = ($usdCurr && $userCurr !== $usdCurr->id)
            ? CurrenciesExchange::RateToday($amountUsd, $usdCurr->id, $userCurr)
            : ($amountUsd * 50); // Fallback rate if exchange table unpopulated

        $invoice = Invoice::create([
            'uuid'         => (string) Str::uuid(),
            'project_id'   => $project->id,
            'user_id'      => $user->id,
            'currency_id'  => $userCurr,
            'status'       => 'unpaid',
            'description'  => $description ?: ('Invoice for project ' . $project->name),
            'subtotal'     => $amountInUserCurrency,
            'tax'          => 0,
            'total'        => $amountInUserCurrency,
            'final_total'  => $amountInUserCurrency,
            'unpaid'       => $amountInUserCurrency,
        ]);

        $project->updateAiContext([
            'current_invoice_id'     => $invoice->id,
            'current_invoice_status' => 'pending',
            'current_stage'          => 'EXECUTION',
            'invoice_confirmed'      => true,
        ]);

        return $invoice;
    }

    /**
     * Execute Approved Task Creation (Triggered after invoice confirmation in EXECUTION stage).
     */
    public function executeApprovedTasks(Project $project, array $tasks): array
    {
        $createdTasks = [];
        $existingTaskNames = Task::where('project_id', $project->id)->pluck('task_name')->toArray();

        foreach ($tasks as $taskData) {
            $title = is_array($taskData) ? ($taskData['title'] ?? 'Developer Task') : (string) $taskData;
            $desc  = is_array($taskData) ? ($taskData['description'] ?? 'Work item generated by AI Software Agency') : 'Work item';

            // Deduplicate task titles
            if (in_array($title, $existingTaskNames, true)) {
                continue;
            }

            $task = Task::create([
                'project_id'       => $project->id,
                'user_id'          => $project->user_id,
                'task_name'        => $title,
                'task_description' => $desc,
                'priority'         => is_array($taskData) ? ($taskData['priority'] ?? 'high') : 'high',
                'due_date'         => now()->addDays(3)->toDateString(),
            ]);

            Todo::create([
                'user_id'       => $project->user_id,
                'project_id'    => $project->id,
                'title'         => $title,
                'priorityColor' => 'indigo',
                'tags'          => '[]',
                'inDate'        => date('Y-m-d'),
                'completed'     => false,
            ]);

            $date = date('Y-m-d');
            $nextSort = (int) (ProjectBoardItem::where('project_id', $project->id)
                ->where('for_date', $date)
                ->max('sort') ?? -1) + 1;

            ProjectBoardItem::create([
                'project_id'    => $project->id,
                'for_date'      => $date,
                'itemable_type' => Task::class,
                'itemable_id'   => $task->id,
                'lane'          => 'backlog',
                'pos_x'         => 24,
                'pos_y'         => 24,
                'sort'          => $nextSort,
                'is_ai'         => true,
            ]);

            $createdTasks[] = $task;
            $existingTaskNames[] = $title;
        }

        return $createdTasks;
    }
}
