<?php

namespace App\Services\AI;

use App\Models\Invoice;
use App\Models\Project;
use App\Models\ProjectBoardItem;
use App\Models\ProjectComment;
use App\Models\Task;
use App\Models\Todo;
use App\Models\User;
use Illuminate\Support\Str;

class AiAgencyLaravelExecutor
{
    /**
     * Execution Phase: Laravel executes all DB operations from the LLM structured JSON decision.
     */
    public function execute(Project $project, array $decision, int $authorId): void
    {
        // 1. Update Project Context incrementally
        if (!empty($decision['context_updates']) && is_array($decision['context_updates'])) {
            $project->updateAiContext($decision['context_updates']);
        }

        // 2. Create Invoice if decision specifies commercial agreement
        if (!empty($decision['create_invoice']['should_create'])) {
            $invoiceData = $decision['create_invoice'];
            $amountUsd   = (float) ($invoiceData['amount_usd'] ?? 450.0);
            $desc        = $invoiceData['description'] ?? ('Invoice for ' . $project->name);

            $user        = User::find($project->user_id) ?? User::find($authorId);
            $userCurr    = $user->currency_id ?? 1;

            $usdCurr = \App\Models\Currency::where('currency', 'USD')->first();
            $amountInUserCurrency = $usdCurr
                ? \App\Models\CurrenciesExchange::RateToday($amountUsd, $usdCurr->id, $userCurr)
                : ($amountUsd * 50); // Fallback multiplier for EGP

            $invoice = Invoice::create([
                'uuid'         => (string) Str::uuid(),
                'project_id'   => $project->id,
                'user_id'      => $user->id,
                'currency_id'  => $userCurr,
                'status'       => 'unpaid',
                'description'  => $desc,
                'subtotal'     => $amountInUserCurrency,
                'tax'          => 0,
                'total'        => $amountInUserCurrency,
                'final_total'  => $amountInUserCurrency,
                'unpaid'       => $amountInUserCurrency,
            ]);

            $project->updateAiContext([
                'current_invoice_id'     => $invoice->id,
                'current_invoice_status' => 'pending',
            ]);
        }

        // 3. Generate Developer Tasks ONLY for missing new features (Rule #9, #10, #11)
        if (!empty($decision['tasks_to_create']) && is_array($decision['tasks_to_create'])) {
            foreach ($decision['tasks_to_create'] as $taskData) {
                $title = $taskData['title'] ?? 'Developer Task';
                $desc  = $taskData['description'] ?? 'Work item generated by AI Software Agency';

                $task = Task::create([
                    'project_id'       => $project->id,
                    'user_id'          => $project->user_id,
                    'task_name'        => $title,
                    'task_description' => $desc,
                    'priority'         => $taskData['priority'] ?? 'high',
                    'due_date'         => now()->addDays(3)->toDateString(),
                ]);

                Todo::create([
                    'user_id'    => $project->user_id,
                    'project_id' => $project->id,
                    'title'      => $title,
                    'completed'  => false,
                ]);

                // Append item to project board continuous timeline
                $date = date('Y-m-d');
                $nextSort = (int) (ProjectBoardItem::where('project_id', $project->id)
                    ->where('for_date', $date)
                    ->max('sort') ?? -1) + 1;

                ProjectBoardItem::create([
                    'project_id'    => $project->id,
                    'for_date'      => $date,
                    'itemable_type' => Task::class,
                    'itemable_id'   => $task->id,
                    'lane'          => 'backlog',
                    'pos_x'         => 24,
                    'pos_y'         => 24,
                    'sort'          => $nextSort,
                    'is_ai'         => true,
                ]);
            }
        }

        // 4. Post natural Arabic AI reply comment to chat thread
        $replyText = $decision['reply'] ?? 'تم استلام طلبك وتحديث بيانات المشروع بنجاح.';
        ProjectComment::create([
            'project_id'       => $project->id,
            'author_id'        => null,
            'guest_name'       => 'AI Project Manager',
            'body'             => $replyText,
            'commentable_type' => Project::class,
            'commentable_id'   => $project->id,
        ]);
    }
}
