<?php

namespace Modules\CRM\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\CRM\app\Traits\BelongsToWorkspace;

class CrmWidget extends Model
{
    use HasFactory, SoftDeletes, BelongsToWorkspace;

    protected $fillable = [
        'workspace_id',
        'name',
        'embed_token',
        'allowed_domains',
        'form_config',
        'is_active',
    ];

    protected $casts = [
        'allowed_domains' => 'array',
        'form_config' => 'array',
        'is_active' => 'boolean',
    ];

    /**
     * Get the leads generated by this widget.
     */
    public function leads()
    {
        return $this->hasMany(Lead::class, 'crm_widget_id');
    }
}
